version: "3"

tasks:
  clean:
    desc: Remove all generated templ files
    cmds:
      - echo "→ Cleaning generated templ files (*_templ.go)"
      - powershell -Command "Get-ChildItem -Recurse -Filter '*_templ.go' | Remove-Item -Force"

  templ:
    desc: Generate templ files
    deps: [clean]
    cmds:
      - echo "→ Generating templ code"
      - templ generate

  run:
    desc: Run dev server (manual)
    deps: [templ]
    cmds:
      - echo "→ Starting dev server"
      - go run ./cmd/dev

  dump:
    desc: Collect all project code into all_code.txt
    deps: [clean]
    cmds:
      - echo "→ Collecting project source into all_code.txt"
      - go run ./tools/collector
      - echo "→ Restoring generated templ files"
      - templ generate  
  test:
    desc: Generate templ code and run all tests
    deps: [templ]
    cmds:
      - echo "→ Running unit tests"
      - go test ./...

  changelog:
    desc: Generate CHANGELOG.md from git history
    cmds:
      - echo "→ Generating CHANGELOG.md"
      - git-chglog -o CHANGELOG.md

  changelog-next:
    desc: Preview CHANGELOG for next version (unreleased changes)
    cmds:
      - echo "→ Preview unreleased changes"
      - git-chglog --next-tag {{.CLI_ARGS}} --output /dev/stdout

  format:
    desc: Format all code (Go and templ)
    cmds:
      - echo "→ Formatting Go code"
      - go fmt ./...
      - echo "→ Formatting templ files"
      - templ fmt .
      - echo "✓ Formatting complete"

  lint:
    desc: Run linters
    cmds:
      - echo "→ Running golangci-lint"
      - golangci-lint run
      - echo "✓ Linting complete"

  setup-hooks:
    desc: Install git hooks
    cmds:
      - echo "→ Setting up git hooks"
      - git config core.hooksPath .githooks
      - echo "✓ Git hooks configured"

  release:
    desc: Create a new release (usage - task release -- v1.1.0)
    cmds:
      - echo "→ Formatting code"
      - task format
      - echo "→ Running tests"
      - task test
      - echo "→ Building project"
      - go build ./...
      - echo "→ Generating CHANGELOG"
      - git-chglog -o CHANGELOG.md --next-tag {{.CLI_ARGS}}
      - echo "→ Committing CHANGELOG"
      - git add CHANGELOG.md
      - git commit -m "chore - Update CHANGELOG for {{.CLI_ARGS}}"
      - echo "→ Creating tag {{.CLI_ARGS}}"
      - git tag {{.CLI_ARGS}}
      - echo "→ Pushing changes and tag"
      - git push origin main
      - git push origin {{.CLI_ARGS}}
      - echo "✅ Release {{.CLI_ARGS}} created! Now run - gh release create {{.CLI_ARGS}}"