// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package elements

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Delete — Bulma delete button.
// Atomic level: ATOM
//
// Delete renders a Bulma `.delete` element as a native <button>.
// It does not contain text, state, or behavior logic.
//
// Any interaction (Alpine.js, aria-*, data-*) must be provided
// via Attr.
type DeleteProps struct {
	// Size defines the delete button size
	// (is-small, is-medium, is-large).
	Size string

	// Attr contains additional HTML attributes
	// for the <button> element.
	Attr templ.Attributes
}

// Delete renders a Bulma delete button.
func Delete(props DeleteProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = BaseElement(
			BaseElementProps{
				Tag:         "button",
				BaseClasses: []string{"delete", props.Size},
				Attr:        props.Attr,
			},
			Items{},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
