// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package elements

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Image — Bulma image component.
// Atomic level: ATOM
//
// Image renders a Bulma `.image` wrapper with a nested `<img>` element.
// It supports fixed sizes, aspect ratios, and rounded images.
//
// This component is layout-oriented and always renders a <figure>
// element as required by Bulma.
type ImageProps struct {
	// Src defines the image source URL.
	// This field is required.
	Src string

	// Alt defines the alternative text for accessibility.
	// This field is required.
	Alt string

	// Ratio defines the aspect ratio modifier
	// (is-square, is-16by9, is-4by3, etc.).
	Ratio string

	// Size defines the fixed image size
	// (is-16x16, is-32x32, is-64x64, etc.).
	Size string

	// Rounded applies the `is-rounded` modifier
	// to the <img> element.
	Rounded bool

	// Attr contains additional HTML attributes
	// for the <img> element.
	Attr templ.Attributes

	// FigureAttr contains additional HTML attributes
	// for the <figure> wrapper.
	FigureAttr templ.Attributes
}

// Image renders a Bulma image component.
func Image(props ImageProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		figureClasses := []string{"image"}
		if props.Ratio != "" {
			figureClasses = append(figureClasses, props.Ratio)
		}
		if props.Size != "" {
			figureClasses = append(figureClasses, props.Size)
		}

		imgClasses := []string{}
		if props.Rounded {
			imgClasses = append(imgClasses, "is-rounded")
		}

		imgAttrs := templ.Attributes{
			"src": props.Src,
			"alt": props.Alt,
		}

		// merge user-provided img attrs (except class — Wrap сам разрулит)
		for k, v := range props.Attr {
			imgAttrs[k] = v
		}
		templ_7745c5c3_Err = BaseElement(
			BaseElementProps{
				Tag:         "figure",
				BaseClasses: figureClasses,
				Attr:        props.FigureAttr,
			},
			Items{
				BaseElement(
					BaseElementProps{
						Tag:         "img",
						BaseClasses: imgClasses,
						Attr:        imgAttrs,
					},
					nil,
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
