// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package elements

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Notification — Bulma notification component.
// Atomic level: ATOM
//
// Notification renders a Bulma `.notification` container.
// It does not manage close buttons, state, or behavior.
//
// Any additional elements (such as a delete button)
// must be composed explicitly by the caller.
type NotificationProps struct {
	// Color defines the Bulma color modifier
	// (is-primary, is-info, is-success, is-warning, is-danger).
	Color string

	// Attr contains additional HTML attributes
	// for the `.notification` container.
	Attr templ.Attributes
}

// Notification renders a Bulma notification container.
func Notification(props NotificationProps, content Items) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = BaseElement(
			BaseElementProps{
				Tag:         "div",
				BaseClasses: []string{"notification", props.Color},
				Attr:        props.Attr,
			},
			content,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
