// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package elements

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Progress — Bulma progress bar.
// Atomic level: ATOM
//
// Progress defines a thin wrapper around the native <progress>
// element styled with Bulma classes.
//
// This component does NOT compute or format progress values.
// Any content rendered inside <progress> is fully controlled
// by the caller, exactly as allowed by Bulma.
type ProgressProps struct {
	// Value defines the current progress value.
	// When nil, the progress bar is rendered in indeterminate mode.
	Value *int

	// Max defines the maximum progress value.
	// When nil, the default browser value is used (typically 100).
	Max *int

	// Color defines the Bulma color modifier
	// (is-primary, is-link, is-info, is-success, etc.).
	Color string

	// Size defines the Bulma size modifier
	// (is-small, is-medium, is-large).
	Size string

	// Attr contains additional HTML attributes
	// for the <progress> element.
	Attr templ.Attributes
}

// Progress renders a Bulma progress bar.
func Progress(props ProgressProps, content Items) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		// Build component classes explicitly
		classes := []string{"progress"}

		if props.Color != "" {
			classes = append(classes, props.Color)
		}
		if props.Size != "" {
			classes = append(classes, props.Size)
		}

		// Copy attributes to avoid mutating input
		attrs := templ.Attributes{}
		for k, v := range props.Attr {
			attrs[k] = v
		}

		if props.Value != nil {
			attrs["value"] = *props.Value
		}
		if props.Max != nil {
			attrs["max"] = *props.Max
		}
		templ_7745c5c3_Err = BaseElement(
			BaseElementProps{
				Tag:         "progress",
				BaseClasses: classes,
				Attr:        attrs,
			},
			content,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
