// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package elements

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Table renders a Bulma `.table` element.
// Atomic level: ATOM
//
// Table defines structural and typographic element.
// It does not manage data, rows, or cells.
// All table markup is provided via content.
//
// Supported modifiers:
// is-bordered, is-striped, is-narrow,
// is-hoverable, is-fullwidth
type TableProps struct {
	// Modifiers contains Bulma table modifiers.
	// Example: "is-striped is-hoverable is-fullwidth"
	Modifiers string

	// Attr contains additional HTML attributes
	// for the <table> element.
	Attr templ.Attributes
}

// Table renders the table element.
func Table(props TableProps, content Items) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = BaseElement(
			BaseElementProps{
				Tag:         "table",
				BaseClasses: []string{"table", props.Modifiers},
				Attr:        props.Attr,
			},
			content,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// TableContainer renders a Bulma `.table-container`.
// Atomic level: ATOM
//
// TableContainer is used to wrap tables
// to enable horizontal scrolling.
type TableContainerProps struct {
	// Attr contains additional HTML attributes
	// for the `.table-container` element.
	Attr templ.Attributes
}

// TableContainer renders the table container.
func TableContainer(props TableContainerProps, content Items) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = BaseElement(
			BaseElementProps{
				Tag:         "div",
				BaseClasses: []string{"table-container"},
				Attr:        props.Attr,
			},
			content,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
