// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package form

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/mtzvd/bulma-templ/elements"

// Select — Bulma select form component.
// Atomic level: ORGANISM
//
// Select renders a Bulma `.select` wrapper together with
// the native `<select>` element inside.
//
// IMPORTANT:
// This component intentionally exposes two separate
// attribute sets:
//
//   - WrapperAttr applies to the `.select` wrapper
//   - Attr applies to the native `<select>` element
//
// This distinction is required because Bulma styles
// and JavaScript hooks (e.g. Alpine.js) are often applied
// to the wrapper, while form-related attributes
// (name, value, data-*, x-model, etc.) must be applied
// to the native control.
//
// Options must be provided via the component content.
type SelectProps struct {
	// Color defines the select color modifier
	// (e.g. is-primary, is-danger).
	Color string

	// Size defines the select size modifier
	// (is-small, is-medium, is-large).
	Size string

	// Multiple enables multiple selection.
	//
	// Note: This affects both the Bulma wrapper
	// and the native <select> element.
	Multiple bool

	// FullWidth adds the is-fullwidth modifier
	// to the Bulma wrapper.
	FullWidth bool

	// Disabled disables the native <select> element.
	Disabled bool

	// Attr contains additional HTML attributes
	// for the native <select> element.
	//
	// Use this for:
	//   - name
	//   - value
	//   - data-*
	//   - x-model
	//   - aria-*
	Attr templ.Attributes

	// WrapperAttr contains additional HTML attributes
	// for the Bulma `.select` wrapper.
	//
	// Use this for:
	//   - layout-related classes
	//   - visibility helpers
	//   - Alpine.js state (x-data, x-show, etc.)
	//   - non-form-related data attributes
	WrapperAttr templ.Attributes
}

// Select renders a Bulma `.select` component.
//
// This component must be wrapped with Control
// and Field components when used in a form layout.
func Select(props SelectProps, content elements.Items) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		// wrapper (.select) classes
		wrapperClasses := []string{"select"}

		if props.Color != "" {
			wrapperClasses = append(wrapperClasses, props.Color)
		}
		if props.Size != "" {
			wrapperClasses = append(wrapperClasses, props.Size)
		}
		if props.Multiple {
			wrapperClasses = append(wrapperClasses, "is-multiple")
		}
		if props.FullWidth {
			wrapperClasses = append(wrapperClasses, "is-fullwidth")
		}

		// select element attrs
		selectAttrs := templ.Attributes{}

		if props.Multiple {
			selectAttrs["multiple"] = "multiple"
		}
		if props.Disabled {
			selectAttrs["disabled"] = "disabled"
		}

		// merge user-provided select attrs
		for k, v := range props.Attr {
			selectAttrs[k] = v
		}
		templ_7745c5c3_Err = elements.BaseElement(
			elements.BaseElementProps{
				Tag:         "div",
				BaseClasses: wrapperClasses,
				Attr:        props.WrapperAttr,
			},
			elements.Items{
				elements.BaseElement(
					elements.BaseElementProps{
						Tag:         "select",
						BaseClasses: nil,
						Attr:        selectAttrs,
					},
					content,
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
