// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/mtzvd/bulma-templ/elements"

// Container — Bulma container layout wrapper.
// Atomic level: MOLECULE
//
// Container constrains the horizontal width of its content
// according to Bulma container rules.
//
// This component does NOT manage grid, columns, or spacing.
// It is intended to be used as a structural layout wrapper.
type ContainerProps struct {
	// Fluid applies the `is-fluid` modifier,
	// making the container full-width.
	Fluid bool

	// Widescreen applies the `is-widescreen` modifier.
	Widescreen bool

	// FullHD applies the `is-fullhd` modifier.
	FullHD bool

	// Attr contains additional HTML attributes
	// for the `.container` element.
	Attr templ.Attributes
}

// Container renders a Bulma `.container` element.
func Container(props ContainerProps, content elements.Items) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		classes := []string{"container"}
		if props.Fluid {
			classes = append(classes, "is-fluid")
		}
		if props.Widescreen {
			classes = append(classes, "is-widescreen")
		}
		if props.FullHD {
			classes = append(classes, "is-fullhd")
		}
		templ_7745c5c3_Err = elements.BaseElement(
			elements.BaseElementProps{
				Tag:         "div",
				BaseClasses: classes,
				Attr:        props.Attr,
			},
			content,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
