// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package grid

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/mtzvd/bulma-templ/elements"

// Grid — Bulma Smart Grid container.
// Atomic level: ORGANISM
//
// Grid renders the Bulma `.grid` container,
// which is based on CSS Grid and provides
// automatic responsive behavior.
//
// Grid does not define column sizes explicitly.
// All layout configuration is done via Bulma
// utility classes passed through Attr.
type GridProps struct {
	// Attr contains additional HTML attributes
	// for the `.grid` container.
	//
	// Use this for:
	//   - grid modifiers (is-col-min-*, is-gap-*)
	//   - responsive classes
	//   - layout helpers
	Attr templ.Attributes
}

// Grid renders a Bulma `.grid` container.
func Grid(props GridProps, content elements.Items) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = elements.BaseElement(
			elements.BaseElementProps{
				Tag:         "div",
				BaseClasses: []string{"grid"},
				Attr:        props.Attr,
			},
			content,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// Cell — Bulma Smart Grid cell.
// Atomic level: MOLECULE
//
// Cell renders the Bulma `.cell` element,
// which defines a single grid item
// inside a Grid container.
type CellProps struct {
	// Attr contains additional HTML attributes
	// for the `.cell` element.
	//
	// Use this for:
	//   - cell span modifiers
	//   - alignment helpers
	//   - responsive behavior
	Attr templ.Attributes
}

// Cell renders a Bulma `.cell` element.
func Cell(props CellProps, content elements.Items) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = elements.BaseElement(
			elements.BaseElementProps{
				Tag:         "div",
				BaseClasses: []string{"cell"},
				Attr:        props.Attr,
			},
			content,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
