// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/mtzvd/bulma-templ/elements"

// Tabs renders a Bulma `.tabs` component.
// Atomic level: ORGANISM
//
// Tabs is used for navigation between sections.
// It defines structural component and does not manage active state.
type TabsProps struct {
	// Centered applies the `is-centered` modifier.
	Centered bool

	// Right applies the `is-right` modifier.
	Right bool

	// Boxed applies the `is-boxed` modifier.
	Boxed bool

	// Toggle applies the `is-toggle` modifier.
	Toggle bool

	// ToggleRounded applies the `is-toggle-rounded` modifier.
	ToggleRounded bool

	// Fullwidth applies the `is-fullwidth` modifier.
	Fullwidth bool

	// Size defines the tabs size
	// (is-small, is-medium, is-large).
	Size string

	// Attr contains additional HTML attributes
	// for the `.tabs` container.
	Attr templ.Attributes
}

// Tabs renders the root `.tabs` container.
func Tabs(props TabsProps, content elements.Items) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		classes := []string{"tabs"}
		if props.Centered {
			classes = append(classes, "is-centered")
		}
		if props.Right {
			classes = append(classes, "is-right")
		}
		if props.Boxed {
			classes = append(classes, "is-boxed")
		}
		if props.Toggle {
			classes = append(classes, "is-toggle")
		}
		if props.ToggleRounded {
			classes = append(classes, "is-toggle-rounded")
		}
		if props.Fullwidth {
			classes = append(classes, "is-fullwidth")
		}
		templ_7745c5c3_Err = elements.BaseElement(
			elements.BaseElementProps{
				Tag:         "div",
				BaseClasses: classes,
				Attr:        props.Attr,
			},
			content,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// TabsList renders the list of tabs.
// Atomic level: MOLECULE
//
// TabsList is always rendered as <ul> inside Tabs.
type TabsListProps struct {
	// Attr contains additional HTML attributes
	// for the <ul> element.
	Attr templ.Attributes
}

// TabsList renders the tabs list container.
func TabsList(props TabsListProps, content elements.Items) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = elements.BaseElement(
			elements.BaseElementProps{
				Tag:  "ul",
				Attr: props.Attr,
			},
			content,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// TabsItem renders a single tab item.
// Atomic level: MOLECULE
//
// Active state is applied on the <li> element
// according to Bulma conventions.
type TabsItemProps struct {
	// Active applies the `is-active` modifier.
	Active bool

	// Attr contains additional HTML attributes
	// for the <li> element.
	Attr templ.Attributes
}

// TabsItem renders a tab item.
func TabsItem(props TabsItemProps, content elements.Items) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		classes := []string{}
		if props.Active {
			classes = append(classes, "is-active")
		}
		templ_7745c5c3_Err = elements.BaseElement(
			elements.BaseElementProps{
				Tag:         "li",
				BaseClasses: classes,
				Attr:        props.Attr,
			},
			content,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// TabsLink renders an interactive tab link.
// Atomic level: ATOM
//
// TabsLink is used inside TabsItem to provide
// correct UX (cursor, hover, focus) as per Bulma docs.
// It does not manage tab state.
type TabsLinkProps struct {
	// Href defines the tab link URL.
	// If empty, TabsLink is rendered as a non-navigational interactive element.
	Href string

	// Attr contains additional HTML attributes
	// for the <a> element.
	Attr templ.Attributes
}

// TabsLink renders a clickable tab element.
func TabsLink(props TabsLinkProps, content elements.Items) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		attrs := templ.Attributes{}
		for k, v := range props.Attr {
			attrs[k] = v
		}
		if props.Href != "" {
			attrs["href"] = props.Href
		}
		templ_7745c5c3_Err = elements.BaseElement(
			elements.BaseElementProps{
				Tag:  "a",
				Attr: attrs,
			},
			content,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
