// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package columns

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/mtzvd/bulma-templ/elements"

// Columns — Bulma columns layout container.
// Atomic level: ORGANISM
//
// Columns defines a flexbox-based layout system
// for arranging content in horizontal columns.
// It does not impose any content structure and
// serves purely as a layout mechanism.
type ColumnsProps struct {
	// Multiline allows columns to wrap onto multiple lines.
	Multiline bool

	// Centered centers the columns horizontally.
	Centered bool

	// Gapless removes the gap between columns.
	Gapless bool

	// Variable enables variable gap sizes.
	Variable bool

	// Attr contains additional HTML attributes
	// for the `.columns` container.
	Attr templ.Attributes
}

// Columns renders a Bulma `.columns` container.
func Columns(props ColumnsProps, content elements.Items) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		classes := []string{"columns"}
		if props.Multiline {
			classes = append(classes, "is-multiline")
		}
		if props.Centered {
			classes = append(classes, "is-centered")
		}
		if props.Gapless {
			classes = append(classes, "is-gapless")
		}
		if props.Variable {
			classes = append(classes, "is-variable")
		}
		templ_7745c5c3_Err = elements.BaseElement(
			elements.BaseElementProps{
				Tag:         "div",
				BaseClasses: classes,
				Attr:        props.Attr,
			},
			content,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// Column — Bulma column element.
// Atomic level: MOLECULE
//
// Column defines a single column inside a Columns container.
// It controls width, offset and responsiveness.
type ColumnProps struct {
	// Size defines the column width
	// (e.g. is-half, is-one-third).
	Size string

	// Narrow makes the column only as wide as its content.
	Narrow bool

	// Offset defines column offset
	// (e.g. is-offset-one-quarter).
	Offset string

	// Attr contains additional HTML attributes
	// for the `.column` element.
	Attr templ.Attributes
}

// Column renders a Bulma `.column` element.
func Column(props ColumnProps, content elements.Items) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		classes := []string{"column"}

		if props.Size != "" {
			classes = append(classes, props.Size)
		}
		if props.Narrow {
			classes = append(classes, "is-narrow")
		}
		if props.Offset != "" {
			classes = append(classes, props.Offset)
		}
		templ_7745c5c3_Err = elements.BaseElement(
			elements.BaseElementProps{
				Tag:         "div",
				BaseClasses: classes,
				Attr:        props.Attr,
			},
			content,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
