// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// BoxExamples — comprehensive demonstration of el.Box component.

// Atomic level: EXAMPLE SHOWCASE

//

// This file demonstrates the Box component from the elements package.

// Box is a simple container with a white background, border, border-radius, and box-shadow.

// It's commonly used for cards, panels, and content containers.

//

// Box supports:

// - No specific props (just wrapper styling)

// - Can contain any content (text, media, components)

// - White background with subtle shadow

// - Rounded corners for modern appearance

//

// Each example shows different use cases for Box.

// The examples follow Bulma-Templ canonical patterns:

// - No Bulma classes in el.Html() - only plain text

// - Props-based configuration via el.BoxProps

// - Semantic HTML wrappers where appropriate

package kitchensink

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	el "github.com/mtzvd/bulma-templ/elements"
	fo "github.com/mtzvd/bulma-templ/form"
	lo "github.com/mtzvd/bulma-templ/layout"
)

// BoxExample1 renders a simple box with text
func BoxExample1() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Box(
			el.BoxProps{},
			el.Items{
				el.Html("I'm in a box."),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// BoxExample1Code returns the source code for BoxExample1
func BoxExample1Code() string {
	return `@el.Box(
	el.BoxProps{},
	el.Items{
		el.Html("I'm in a box."),
	},
)`
}

// BoxExample2 renders a box with a form
func BoxExample2() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Box(
			el.BoxProps{},
			el.Items{
				fo.Field(
					fo.FieldProps{},
					el.Items{
						fo.Label(fo.LabelProps{Text: "Email"}),
						fo.Control(
							fo.ControlProps{},
							el.Items{
								fo.Input(fo.InputProps{
									Type:        "email",
									Placeholder: "e.g. alex@example.com",
								}),
							},
						),
					},
				),
				fo.Field(
					fo.FieldProps{},
					el.Items{
						fo.Label(fo.LabelProps{Text: "Password"}),
						fo.Control(
							fo.ControlProps{},
							el.Items{
								fo.Input(fo.InputProps{
									Type:        "password",
									Placeholder: "********",
								}),
							},
						),
					},
				),
				el.Button(
					el.ButtonProps{Color: "is-primary"},
					el.Items{el.Html("Sign in")},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// BoxExample2Code returns the source code for BoxExample2
func BoxExample2Code() string {
	return `@el.Box(
	el.BoxProps{},
	el.Items{
		fo.Field(
			fo.FieldProps{},
			el.Items{
				fo.Label(fo.LabelProps{Text: "Email"}),
				fo.Control(
					fo.ControlProps{},
					el.Items{
						fo.Input(fo.InputProps{
							Type:        "email",
							Placeholder: "e.g. alex@example.com",
						}),
					},
				),
			},
		),
		fo.Field(
			fo.FieldProps{},
			el.Items{
				fo.Label(fo.LabelProps{Text: "Password"}),
				fo.Control(
					fo.ControlProps{},
					el.Items{
						fo.Input(fo.InputProps{
							Type:        "password",
							Placeholder: "********",
						}),
					},
				),
			},
		),
		el.Button(
			el.ButtonProps{Color: "is-primary"},
			el.Items{el.Html("Sign in")},
		),
	},
)`
}

// BoxExample3 renders a box with media object
func BoxExample3() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Box(
			el.BoxProps{},
			el.Items{
				lo.Media(
					lo.MediaProps{},
					el.Items{
						lo.MediaLeft(
							lo.MediaLeftProps{},
							el.Items{
								el.Image(
									el.ImageProps{
										Size: "is-64x64",
										Src:  "https://bulma.io/assets/images/placeholders/128x128.png",
										Alt:  "Image",
									},
								),
							},
						),
						lo.MediaContent(
							lo.MediaContentProps{},
							el.Items{
								el.Html(`
								<p>
									<strong>John Smith</strong> <small>@johnsmith</small> <small>31m</small>
									<br>
									Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean efficitur sit amet massa fringilla egestas.
								</p>
							`),
							},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// BoxExample3Code returns the source code for BoxExample3
func BoxExample3Code() string {
	return `@el.Box(
	el.BoxProps{},
	el.Items{
		lo.Media(
			lo.MediaProps{},
			el.Items{
				lo.MediaLeft(
					lo.MediaLeftProps{},
					el.Items{
						el.Image(
							el.ImageProps{
								Size: "is-64x64",
								Src:  "https://bulma.io/.../128x128.png",
								Alt:  "Image",
							},
						),
					},
				),
				lo.MediaContent(
					lo.MediaContentProps{},
					el.Items{
						el.Html(` + "`" + `
							<p>
								<strong>John Smith</strong> <small>@johnsmith</small>
								<br>
								Lorem ipsum dolor sit amet...
							</p>
						` + "`" + `),
					},
				),
			},
		),
	},
)`
}

// BoxExamples showcases Box component variations.
// Demonstrates different content types inside Box containers.
func BoxExamples() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Block(el.BlockProps{}, el.Items{TitleH3("is-4", "Box")}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		// Define all box examples with their codes
		examples := []ComponentItem{
			{ID: "box-1", Code: BoxExample1Code(), Component: BoxExample1()},
			{ID: "box-2", Code: BoxExample2Code(), Component: BoxExample2()},
			{ID: "box-3", Code: BoxExample3Code(), Component: BoxExample3()},
		}
		for _, example := range examples {
			templ_7745c5c3_Err = ExampleWithCode(example.ID, example.Code, example.Component).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
