// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package kitchensink

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	co "github.com/mtzvd/bulma-templ/components"
	el "github.com/mtzvd/bulma-templ/elements"
)

func BreadcrumbExamples() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Block(el.BlockProps{}, el.Items{TitleH3("is-4", "Breadcrumb")}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Default (slash separator)").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Breadcrumb(
			co.BreadcrumbProps{},
			el.Items{
				el.Html(`
				<ul>
					<li><a href="#">Home</a></li>
					<li><a href="#">Documents</a></li>
					<li><a href="#">Projects</a></li>
					<li class="is-active"><a href="#" aria-current="page">Current</a></li>
				</ul>
			`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("With arrow separator").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Breadcrumb(
			co.BreadcrumbProps{Separator: "has-arrow-separator"},
			el.Items{
				el.Html(`
				<ul>
					<li><a href="#">Products</a></li>
					<li><a href="#">Electronics</a></li>
					<li class="is-active"><a href="#" aria-current="page">Laptops</a></li>
				</ul>
			`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("With bullet separator").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Breadcrumb(
			co.BreadcrumbProps{Separator: "has-bullet-separator"},
			el.Items{
				el.Html(`
				<ul>
					<li><a href="#">Admin</a></li>
					<li><a href="#">Users</a></li>
					<li class="is-active"><a href="#" aria-current="page">Settings</a></li>
				</ul>
			`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("With dot separator").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Breadcrumb(
			co.BreadcrumbProps{Separator: "has-dot-separator"},
			el.Items{
				el.Html(`
				<ul>
					<li><a href="#">Blog</a></li>
					<li><a href="#">Category</a></li>
					<li class="is-active"><a href="#" aria-current="page">Article</a></li>
				</ul>
			`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("With succeeds separator").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Breadcrumb(
			co.BreadcrumbProps{Separator: "has-succeeds-separator"},
			el.Items{
				el.Html(`
				<ul>
					<li><a href="#">Library</a></li>
					<li><a href="#">Books</a></li>
					<li class="is-active"><a href="#" aria-current="page">Fiction</a></li>
				</ul>
			`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Centered alignment").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Breadcrumb(
			co.BreadcrumbProps{
				Attr: templ.Attributes{"class": "is-centered"},
			},
			el.Items{
				el.Html(`
				<ul>
					<li><a href="#">Home</a></li>
					<li><a href="#">Section</a></li>
					<li class="is-active"><a href="#" aria-current="page">Page</a></li>
				</ul>
			`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Right alignment").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Breadcrumb(
			co.BreadcrumbProps{
				Attr: templ.Attributes{"class": "is-right"},
			},
			el.Items{
				el.Html(`
				<ul>
					<li><a href="#">Start</a></li>
					<li><a href="#">Middle</a></li>
					<li class="is-active"><a href="#" aria-current="page">End</a></li>
				</ul>
			`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Small size").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Breadcrumb(
			co.BreadcrumbProps{
				Attr: templ.Attributes{"class": "is-small"},
			},
			el.Items{
				el.Html(`
				<ul>
					<li><a href="#">Dashboard</a></li>
					<li><a href="#">Reports</a></li>
					<li class="is-active"><a href="#" aria-current="page">Analytics</a></li>
				</ul>
			`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Medium size").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Breadcrumb(
			co.BreadcrumbProps{
				Attr: templ.Attributes{"class": "is-medium"},
			},
			el.Items{
				el.Html(`
				<ul>
					<li><a href="#">Store</a></li>
					<li><a href="#">Products</a></li>
					<li class="is-active"><a href="#" aria-current="page">Details</a></li>
				</ul>
			`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Large size").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Breadcrumb(
			co.BreadcrumbProps{
				Attr: templ.Attributes{"class": "is-large"},
			},
			el.Items{
				el.Html(`
				<ul>
					<li><a href="#">Company</a></li>
					<li><a href="#">Team</a></li>
					<li class="is-active"><a href="#" aria-current="page">Members</a></li>
				</ul>
			`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("With icons").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Breadcrumb(
			co.BreadcrumbProps{},
			el.Items{
				co.BreadcrumbList(
					co.BreadcrumbListProps{},
					el.Items{
						co.BreadcrumbItem(
							co.BreadcrumbItemProps{},
							el.Items{
								co.BreadcrumbLink(
									co.BreadcrumbLinkProps{Href: "#"},
									el.Items{
										co.BreadcrumbIcon(co.BreadcrumbIconProps{
											Icon: el.IconProps{IconClass: "fas fa-home"},
										}),
										el.Html("<span>Home</span>"),
									},
								),
							},
						),
						co.BreadcrumbItem(
							co.BreadcrumbItemProps{},
							el.Items{
								co.BreadcrumbLink(
									co.BreadcrumbLinkProps{Href: "#"},
									el.Items{
										co.BreadcrumbIcon(co.BreadcrumbIconProps{
											Icon: el.IconProps{IconClass: "fas fa-book"},
										}),
										el.Html("<span>Documentation</span>"),
									},
								),
							},
						),
						co.BreadcrumbItem(
							co.BreadcrumbItemProps{},
							el.Items{
								co.BreadcrumbLink(
									co.BreadcrumbLinkProps{Href: "#"},
									el.Items{
										co.BreadcrumbIcon(co.BreadcrumbIconProps{
											Icon: el.IconProps{IconClass: "fas fa-puzzle-piece"},
										}),
										el.Html("<span>Components</span>"),
									},
								),
							},
						),
						co.BreadcrumbItem(
							co.BreadcrumbItemProps{Active: true},
							el.Items{
								co.BreadcrumbLink(
									co.BreadcrumbLinkProps{Current: true},
									el.Items{
										co.BreadcrumbIcon(co.BreadcrumbIconProps{
											Icon: el.IconProps{IconClass: "fas fa-thumbs-up"},
										}),
										el.Html("<span>Breadcrumb</span>"),
									},
								),
							},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
