// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// ButtonExamples — comprehensive demonstration of el.Button component.

// Atomic level: EXAMPLE SHOWCASE

//

// This file demonstrates all major variations of the Button component from the elements package.

// Button is one of the most versatile UI elements in Bulma, supporting:

// - Color variations (7 semantic colors + default)

// - Size variations (small, normal, medium, large)

// - State modifiers (loading, disabled, active)

// - Layout options (full-width)

//

// Each example is grouped by property category with explanatory comments.

// The examples follow Bulma-Templ canonical patterns:

// - No Bulma classes in el.Html() - only plain text

// - Structural wrapper (<div class="buttons">) for button groups

// - Props-based configuration via el.ButtonProps

// - Semantic HTML wrappers for titles (TitleH3)

package kitchensink

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import el "github.com/mtzvd/bulma-templ/elements"

// ButtonExample1 demonstrates button color variations.
// Bulma provides 7 semantic color modifiers for buttons.
func ButtonExample1() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Buttons(
			el.ButtonsProps{},
			el.Items{
				el.Button(
					el.ButtonProps{},
					el.Items{el.Html("Default")},
				),
				el.Button(
					el.ButtonProps{Color: "is-primary"},
					el.Items{el.Html("Primary")},
				),
				el.Button(
					el.ButtonProps{Color: "is-link"},
					el.Items{el.Html("Link")},
				),
				el.Button(
					el.ButtonProps{Color: "is-info"},
					el.Items{el.Html("Info")},
				),
				el.Button(
					el.ButtonProps{Color: "is-success"},
					el.Items{el.Html("Success")},
				),
				el.Button(
					el.ButtonProps{Color: "is-warning"},
					el.Items{el.Html("Warning")},
				),
				el.Button(
					el.ButtonProps{Color: "is-danger"},
					el.Items{el.Html("Danger")},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func ButtonExample1Code() string {
	return `@el.Buttons(
	el.ButtonsProps{},
	el.Items{
		el.Button(
			el.ButtonProps{},
			el.Items{el.Html("Default")},
		),
		el.Button(
			el.ButtonProps{Color: "is-primary"},
			el.Items{el.Html("Primary")},
		),
		el.Button(
			el.ButtonProps{Color: "is-link"},
			el.Items{el.Html("Link")},
		),
		el.Button(
			el.ButtonProps{Color: "is-info"},
			el.Items{el.Html("Info")},
		),
		el.Button(
			el.ButtonProps{Color: "is-success"},
			el.Items{el.Html("Success")},
		),
		el.Button(
			el.ButtonProps{Color: "is-warning"},
			el.Items{el.Html("Warning")},
		),
		el.Button(
			el.ButtonProps{Color: "is-danger"},
			el.Items{el.Html("Danger")},
		),
	},
)`
}

// ButtonExample2 demonstrates button size variations.
// Bulma provides 4 size modifiers: small, normal, medium, large.
func ButtonExample2() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Buttons(
			el.ButtonsProps{},
			el.Items{
				el.Button(
					el.ButtonProps{Size: "is-small", Color: "is-primary"},
					el.Items{el.Html("Small")},
				),
				el.Button(
					el.ButtonProps{Color: "is-primary"},
					el.Items{el.Html("Normal")},
				),
				el.Button(
					el.ButtonProps{Size: "is-medium", Color: "is-primary"},
					el.Items{el.Html("Medium")},
				),
				el.Button(
					el.ButtonProps{Size: "is-large", Color: "is-primary"},
					el.Items{el.Html("Large")},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func ButtonExample2Code() string {
	return `@el.Buttons(
	el.ButtonsProps{},
	el.Items{
		el.Button(
			el.ButtonProps{Size: "is-small", Color: "is-primary"},
			el.Items{el.Html("Small")},
		),
		el.Button(
			el.ButtonProps{Color: "is-primary"},
			el.Items{el.Html("Normal")},
		),
		el.Button(
			el.ButtonProps{Size: "is-medium", Color: "is-primary"},
			el.Items{el.Html("Medium")},
		),
		el.Button(
			el.ButtonProps{Size: "is-large", Color: "is-primary"},
			el.Items{el.Html("Large")},
		),
	},
)`
}

// ButtonExample3 demonstrates button state variations.
// States include loading, disabled, and active.
func ButtonExample3() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Buttons(
			el.ButtonsProps{},
			el.Items{
				el.Button(
					el.ButtonProps{Color: "is-primary", State: "is-loading"},
					el.Items{el.Html("Loading")},
				),
				el.Button(
					el.ButtonProps{Color: "is-primary", Disabled: true},
					el.Items{el.Html("Disabled")},
				),
				el.Button(
					el.ButtonProps{Color: "is-primary", State: "is-active"},
					el.Items{el.Html("Active")},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func ButtonExample3Code() string {
	return `@el.Buttons(
	el.ButtonsProps{},
	el.Items{
		el.Button(
			el.ButtonProps{Color: "is-primary", State: "is-loading"},
			el.Items{el.Html("Loading")},
		),
		el.Button(
			el.ButtonProps{Color: "is-primary", Disabled: true},
			el.Items{el.Html("Disabled")},
		),
		el.Button(
			el.ButtonProps{Color: "is-primary", State: "is-active"},
			el.Items{el.Html("Active")},
		),
	},
)`
}

// ButtonExample4 demonstrates full width button layout.
// FullWidth modifier makes button expand to 100% of parent container width.
func ButtonExample4() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Button(
			el.ButtonProps{Color: "is-primary", FullWidth: true},
			el.Items{el.Html("Full Width Button")},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func ButtonExample4Code() string {
	return `@el.Button(
	el.ButtonProps{Color: "is-primary", FullWidth: true},
	el.Items{el.Html("Full Width Button")},
)`
}

// ButtonExamples showcases all Button component variations.
// Demonstrates color, size, state, and layout properties.
func ButtonExamples() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Block(el.BlockProps{}, el.Items{TitleH3("is-4", "Button")}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		examples := []ComponentItem{
			{ID: "button-colors", Code: ButtonExample1Code(), Component: ButtonExample1()},
			{ID: "button-sizes", Code: ButtonExample2Code(), Component: ButtonExample2()},
			{ID: "button-states", Code: ButtonExample3Code(), Component: ButtonExample3()},
			{ID: "button-fullwidth", Code: ButtonExample4Code(), Component: ButtonExample4()},
		}
		for _, example := range examples {
			templ_7745c5c3_Err = ExampleWithCode(example.ID, example.Code, example.Component).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
