// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// CardExamples — comprehensive demonstration of co.Card component family.

// Atomic level: EXAMPLE SHOWCASE

//

// This file demonstrates the Card components from the components package.

// Card is a flexible content container with header, content, image, and footer sections.

// Perfect for blog posts, products, profiles, and any structured content.

//

// Card family components:

// - Card: Main container

// - CardHeader: Optional top section with title

// - CardHeaderTitle: Title within header

// - CardImage: Image section (typically at top)

// - CardContent: Main content area

// - CardFooter: Optional bottom section

// - CardFooterItem: Clickable footer items

//

// Each example shows different card configurations.

// The examples follow Bulma-Templ canonical patterns:

// - Props-based configuration

// - Compose cards from smaller components

// - Use Columns for side-by-side cards

package kitchensink

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	co "github.com/mtzvd/bulma-templ/components"
	el "github.com/mtzvd/bulma-templ/elements"
)

// CardExamples showcases Card component variations following Bulma documentation.
// Demonstrates header, image, content, and footer sections.
func CardExamples() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Block(el.BlockProps{}, el.Items{TitleH3("is-4", "Card")}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Card with header, content and footer").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Block(
			el.BlockProps{Attr: templ.Attributes{"style": "max-width: 400px;"}},
			el.Items{
				co.Card(
					co.CardProps{},
					el.Items{
						co.CardHeader(
							co.CardHeaderProps{},
							el.Items{
								co.CardHeaderTitle(
									co.CardHeaderTitleProps{},
									el.Items{el.Html("Component")},
								),
								el.Html(`
								<button class="card-header-icon" aria-label="more options">
									<span class="icon">
										<i class="fas fa-angle-down" aria-hidden="true"></i>
									</span>
								</button>
							`),
							},
						),
						co.CardContent(
							co.CardContentProps{},
							el.Items{
								el.Content(
									el.ContentProps{},
									el.Items{
										el.Html(`
										Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec iaculis mauris.
										<a href="#">@bulmaio</a>. <a href="#">#css</a> <a href="#">#responsive</a>
										<br>
										<time datetime="2016-1-1">11:09 PM - 1 Jan 2016</time>
									`),
									},
								),
							},
						),
						co.CardFooter(
							co.CardFooterProps{},
							el.Items{
								co.CardFooterItem(
									co.CardFooterItemProps{Attr: templ.Attributes{"href": "#"}},
									el.Items{el.Html("Save")},
								),
								co.CardFooterItem(
									co.CardFooterItemProps{Attr: templ.Attributes{"href": "#"}},
									el.Items{el.Html("Edit")},
								),
								co.CardFooterItem(
									co.CardFooterItemProps{Attr: templ.Attributes{"href": "#"}},
									el.Items{el.Html("Delete")},
								),
							},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Card with quote").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Block(
			el.BlockProps{Attr: templ.Attributes{"style": "max-width: 400px;"}},
			el.Items{
				co.Card(
					co.CardProps{},
					el.Items{
						co.CardContent(
							co.CardContentProps{},
							el.Items{
								el.Html(`
								<p class="title">
									"There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors."
								</p>
								<p class="subtitle">Jeff Atwood</p>
							`),
							},
						),
						co.CardFooter(
							co.CardFooterProps{},
							el.Items{
								el.Html(`
								<p class="card-footer-item">
									<span>
										View on <a href="https://twitter.com/codinghorror/status/506010907021828096">Twitter</a>
									</span>
								</p>
								<p class="card-footer-item">
									<span>Share on <a href="#">Facebook</a></span>
								</p>
							`),
							},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Card with image and media content").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Block(
			el.BlockProps{Attr: templ.Attributes{"style": "max-width: 400px;"}},
			el.Items{
				co.Card(
					co.CardProps{},
					el.Items{
						el.Html(`
						<div class="card-image">
							<figure class="image is-4by3">
								<img src="https://bulma.io/assets/images/placeholders/1280x960.png" alt="Placeholder image">
							</figure>
						</div>
					`),
						co.CardContent(
							co.CardContentProps{},
							el.Items{
								el.Html(`
								<div class="media">
									<div class="media-left">
										<figure class="image is-48x48">
											<img src="https://bulma.io/assets/images/placeholders/96x96.png" alt="Placeholder image">
										</figure>
									</div>
									<div class="media-content">
										<p class="title is-4">John Smith</p>
										<p class="subtitle is-6">@johnsmith</p>
									</div>
								</div>
								<div class="content">
									Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec iaculis mauris.
									<a>@bulmaio</a>. <a href="#">#css</a> <a href="#">#responsive</a>
									<br>
									<time datetime="2016-1-1">11:09 PM - 1 Jan 2016</time>
								</div>
							`),
							},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Card parts: Header only").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Block(
			el.BlockProps{Attr: templ.Attributes{"style": "max-width: 400px;"}},
			el.Items{
				co.Card(
					co.CardProps{},
					el.Items{
						co.CardHeader(
							co.CardHeaderProps{},
							el.Items{
								co.CardHeaderTitle(
									co.CardHeaderTitleProps{},
									el.Items{el.Html("Card header")},
								),
								el.Html(`
								<button class="card-header-icon" aria-label="more options">
									<span class="icon">
										<i class="fas fa-angle-down" aria-hidden="true"></i>
									</span>
								</button>
							`),
							},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Card parts: Image only").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Block(
			el.BlockProps{Attr: templ.Attributes{"style": "max-width: 400px;"}},
			el.Items{
				co.Card(
					co.CardProps{},
					el.Items{
						el.Html(`
						<div class="card-image">
							<figure class="image is-4by3">
								<img src="https://bulma.io/assets/images/placeholders/1280x960.png" alt="Placeholder image">
							</figure>
						</div>
					`),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Card parts: Content only").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Block(
			el.BlockProps{Attr: templ.Attributes{"style": "max-width: 400px;"}},
			el.Items{
				co.Card(
					co.CardProps{},
					el.Items{
						co.CardContent(
							co.CardContentProps{},
							el.Items{
								el.Content(
									el.ContentProps{},
									el.Items{
										el.Html(`
										Lorem ipsum leo risus, porta ac consectetur ac, vestibulum at eros. Donec id elit non mi porta gravida at eget metus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras mattis consectetur purus sit amet fermentum.
									`),
									},
								),
							},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Card parts: Footer only").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Block(
			el.BlockProps{Attr: templ.Attributes{"style": "max-width: 400px;"}},
			el.Items{
				co.Card(
					co.CardProps{},
					el.Items{
						co.CardFooter(
							co.CardFooterProps{},
							el.Items{
								co.CardFooterItem(
									co.CardFooterItemProps{Attr: templ.Attributes{"href": "#"}},
									el.Items{el.Html("Save")},
								),
								co.CardFooterItem(
									co.CardFooterItemProps{Attr: templ.Attributes{"href": "#"}},
									el.Items{el.Html("Edit")},
								),
								co.CardFooterItem(
									co.CardFooterItemProps{Attr: templ.Attributes{"href": "#"}},
									el.Items{el.Html("Delete")},
								),
							},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
