// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// ColumnsExamples — comprehensive demonstration of cl.Columns and cl.Column components.

// Atomic level: EXAMPLE SHOWCASE

//

// This file demonstrates the Columns system from the columns package.

// Columns provides flexbox-based responsive grid layout.

//

// Columns props:

// - Multiline: Boolean for wrapping columns

// - Centered: Boolean to center columns

// - VCentered: Boolean to vertically center columns

// - Mobile, Tablet, Desktop: Boolean for breakpoint control

// - Gap: Gap size (0-8)

//

// Column props:

// - Size: Width (is-half, is-one-third, is-one-quarter, is-narrow, etc)

// - Offset: Left margin (is-offset-one-quarter, etc)

package kitchensink

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	cl "github.com/mtzvd/bulma-templ/columns"
	el "github.com/mtzvd/bulma-templ/elements"
)

// ColumnsExamples showcases Columns system variations.
func ColumnsExamples() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Block(el.BlockProps{}, el.Items{TitleH3("is-4", "Columns")}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Basic columns").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = cl.Columns(
			cl.ColumnsProps{},
			el.Items{
				cl.Column(
					cl.ColumnProps{},
					el.Items{
						el.Notification(
							el.NotificationProps{Color: "is-primary"},
							el.Items{el.Html("Column 1")},
						),
					},
				),
				cl.Column(
					cl.ColumnProps{},
					el.Items{
						el.Notification(
							el.NotificationProps{Color: "is-info"},
							el.Items{el.Html("Column 2")},
						),
					},
				),
				cl.Column(
					cl.ColumnProps{},
					el.Items{
						el.Notification(
							el.NotificationProps{Color: "is-success"},
							el.Items{el.Html("Column 3")},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Custom column sizes").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = cl.Columns(
			cl.ColumnsProps{},
			el.Items{
				cl.Column(
					cl.ColumnProps{Size: "is-half"},
					el.Items{
						el.Notification(
							el.NotificationProps{Color: "is-warning"},
							el.Items{el.Html("is-half")},
						),
					},
				),
				cl.Column(
					cl.ColumnProps{},
					el.Items{
						el.Notification(
							el.NotificationProps{Color: "is-link"},
							el.Items{el.Html("Auto")},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Multiline columns").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = cl.Columns(
			cl.ColumnsProps{Multiline: true},
			el.Items{
				cl.Column(
					cl.ColumnProps{Size: "is-one-quarter"},
					el.Items{
						el.Notification(
							el.NotificationProps{Color: "is-primary"},
							el.Items{el.Html("1/4")},
						),
					},
				),
				cl.Column(
					cl.ColumnProps{Size: "is-one-quarter"},
					el.Items{
						el.Notification(
							el.NotificationProps{Color: "is-primary"},
							el.Items{el.Html("1/4")},
						),
					},
				),
				cl.Column(
					cl.ColumnProps{Size: "is-one-quarter"},
					el.Items{
						el.Notification(
							el.NotificationProps{Color: "is-primary"},
							el.Items{el.Html("1/4")},
						),
					},
				),
				cl.Column(
					cl.ColumnProps{Size: "is-one-quarter"},
					el.Items{
						el.Notification(
							el.NotificationProps{Color: "is-primary"},
							el.Items{el.Html("1/4")},
						),
					},
				),
				cl.Column(
					cl.ColumnProps{Size: "is-half"},
					el.Items{
						el.Notification(
							el.NotificationProps{Color: "is-info"},
							el.Items{el.Html("1/2")},
						),
					},
				),
				cl.Column(
					cl.ColumnProps{Size: "is-one-quarter"},
					el.Items{
						el.Notification(
							el.NotificationProps{Color: "is-success"},
							el.Items{el.Html("1/4")},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Centered columns").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = cl.Columns(
			cl.ColumnsProps{Centered: true},
			el.Items{
				cl.Column(
					cl.ColumnProps{Size: "is-half"},
					el.Items{
						el.Notification(
							el.NotificationProps{Color: "is-danger"},
							el.Items{el.Html("Centered")},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
