// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// DeleteExamples — comprehensive demonstration of el.Delete component.

// Atomic level: EXAMPLE SHOWCASE

//

// This file demonstrates the Delete component from the elements package.

// Delete is a circular close/remove button commonly used in notifications, modals, and tags.

// It uses a cross icon (×) and is purely visual - functionality must be added via JavaScript.

//

// Delete supports:

// - Size variations (small, normal, medium, large)

// - No color variations (always dark cross on transparent background)

// - Hover/active states built-in

//

// Each example shows different sizes and contexts for Delete button.

// The examples follow Bulma-Templ canonical patterns:

// - No Bulma classes in el.Html() - only plain text

// - Props-based configuration via el.DeleteProps

// - Delete is a self-contained component with no children

package kitchensink

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	el "github.com/mtzvd/bulma-templ/elements"
)

// DeleteExample1 demonstrates delete button size variations.
// Delete supports 4 size modifiers: small, normal, medium, large.
func DeleteExample1() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Block(
			el.BlockProps{},
			el.Items{
				el.Delete(el.DeleteProps{}),
				el.Delete(el.DeleteProps{Size: "is-small"}),
				el.Delete(el.DeleteProps{Size: "is-medium"}),
				el.Delete(el.DeleteProps{Size: "is-large"}),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func DeleteExample1Code() string {
	return `@el.Block(
	el.BlockProps{},
	el.Items{
		el.Delete(el.DeleteProps{}),
		el.Delete(el.DeleteProps{Size: "is-small"}),
		el.Delete(el.DeleteProps{Size: "is-medium"}),
		el.Delete(el.DeleteProps{Size: "is-large"}),
	},
)`
}

// DeleteExample2 demonstrates delete button in notification context.
// Delete is positioned in the top-right corner of notifications.
func DeleteExample2() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Notification(
			el.NotificationProps{Color: "is-warning"},
			el.Items{
				el.Delete(el.DeleteProps{}),
				el.Html("Notification with delete button"),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func DeleteExample2Code() string {
	return `@el.Notification(
	el.NotificationProps{Color: "is-warning"},
	el.Items{
		el.Delete(el.DeleteProps{}),
		el.Html("Notification with delete button"),
	},
)`
}

// DeleteExamples showcases Delete component variations.
// Demonstrates size options and common use cases.
func DeleteExamples() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Block(el.BlockProps{}, el.Items{TitleH3("is-4", "Delete")}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		examples := []ComponentItem{
			{ID: "delete-sizes", Code: DeleteExample1Code(), Component: DeleteExample1()},
			{ID: "delete-notification", Code: DeleteExample2Code(), Component: DeleteExample2()},
		}
		for _, example := range examples {
			templ_7745c5c3_Err = ExampleWithCode(example.ID, example.Code, example.Component).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
