// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// DropdownExamples — comprehensive demonstration of co.Dropdown component family.

// Atomic level: EXAMPLE SHOWCASE

//

// This file demonstrates the Dropdown components from the components package.

// Dropdown provides a toggleable menu with items, dividers, and active states.

// Requires JavaScript for click-to-toggle, but supports hover-only mode.

//

// Dropdown family:

// - Dropdown: Main container

// - DropdownTrigger: Button that triggers menu

// - DropdownMenu: Menu container

// - DropdownItem: Individual menu items

// - DropdownDivider: Separator between items

//

// Props:

// - Hoverable: Open on hover instead of click

// - Active: CSS class for active items

// - Href: Link destination for items

package kitchensink

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	co "github.com/mtzvd/bulma-templ/components"
	el "github.com/mtzvd/bulma-templ/elements"
)

// DropdownExamples showcases Dropdown component variations.
func DropdownExamples() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Block(el.BlockProps{}, el.Items{TitleH3("is-4", "Dropdown")}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Hoverable dropdown").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Block(
			el.BlockProps{},
			el.Items{
				co.Dropdown(
					co.DropdownProps{Hoverable: true},
					el.Items{
						co.DropdownTrigger(
							co.DropdownTriggerProps{},
							el.Items{
								el.Button(
									el.ButtonProps{},
									el.Items{
										el.Html("<span>Hover me</span>"),
										el.Icon(el.IconProps{IconClass: "fas fa-angle-down"}),
									},
								),
							},
						),
						co.DropdownMenu(
							co.DropdownMenuProps{},
							el.Items{
								co.DropdownItem(
									co.DropdownItemProps{Href: "#"},
									el.Items{el.Html("Dropdown item")},
								),
								co.DropdownItem(
									co.DropdownItemProps{Href: "#", Active: true},
									el.Items{el.Html("Active item")},
								),
								co.DropdownItem(
									co.DropdownItemProps{Href: "#"},
									el.Items{el.Html("Another item")},
								),
								co.DropdownDivider(),
								co.DropdownItem(
									co.DropdownItemProps{Href: "#"},
									el.Items{el.Html("With a divider")},
								),
							},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Right-aligned dropdown").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Block(
			el.BlockProps{},
			el.Items{
				co.Dropdown(
					co.DropdownProps{Hoverable: true, Right: true},
					el.Items{
						co.DropdownTrigger(
							co.DropdownTriggerProps{},
							el.Items{
								el.Button(
									el.ButtonProps{},
									el.Items{
										el.Html("<span>Right aligned</span>"),
										el.Icon(el.IconProps{IconClass: "fas fa-angle-down"}),
									},
								),
							},
						),
						co.DropdownMenu(
							co.DropdownMenuProps{},
							el.Items{
								co.DropdownItem(
									co.DropdownItemProps{Href: "#"},
									el.Items{el.Html("Overview")},
								),
								co.DropdownItem(
									co.DropdownItemProps{Href: "#"},
									el.Items{el.Html("Modifiers")},
								),
								co.DropdownItem(
									co.DropdownItemProps{Href: "#"},
									el.Items{el.Html("Grid")},
								),
								co.DropdownItem(
									co.DropdownItemProps{Href: "#"},
									el.Items{el.Html("Elements")},
								),
							},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Dropup (opens upward)").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Block(
			el.BlockProps{},
			el.Items{
				co.Dropdown(
					co.DropdownProps{Hoverable: true, Up: true},
					el.Items{
						co.DropdownTrigger(
							co.DropdownTriggerProps{},
							el.Items{
								el.Button(
									el.ButtonProps{},
									el.Items{
										el.Html("<span>Dropup button</span>"),
										el.Icon(el.IconProps{IconClass: "fas fa-angle-up"}),
									},
								),
							},
						),
						co.DropdownMenu(
							co.DropdownMenuProps{},
							el.Items{
								co.DropdownItem(
									co.DropdownItemProps{Href: "#"},
									el.Items{el.Html("Dropdown item")},
								),
								co.DropdownItem(
									co.DropdownItemProps{Href: "#"},
									el.Items{el.Html("Other item")},
								),
								co.DropdownItem(
									co.DropdownItemProps{Href: "#"},
									el.Items{el.Html("Another item")},
								),
							},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Dropdown with content").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Block(
			el.BlockProps{},
			el.Items{
				co.Dropdown(
					co.DropdownProps{Hoverable: true},
					el.Items{
						co.DropdownTrigger(
							co.DropdownTriggerProps{},
							el.Items{
								el.Button(
									el.ButtonProps{},
									el.Items{
										el.Html("<span>Content</span>"),
										el.Icon(el.IconProps{IconClass: "fas fa-angle-down"}),
									},
								),
							},
						),
						co.DropdownMenu(
							co.DropdownMenuProps{},
							el.Items{
								el.Html(`
								<div class="dropdown-item">
									<p>You can insert <strong>any type of content</strong> within the dropdown menu.</p>
								</div>
								<hr class="dropdown-divider">
								<div class="dropdown-item">
									<p>You simply need to use a <code>&lt;div&gt;</code> instead.</p>
								</div>
							`),
								co.DropdownItem(
									co.DropdownItemProps{Href: "#"},
									el.Items{el.Html("This is a link")},
								),
							},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
