// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// FieldExamples — comprehensive demonstration of fo.Field component.

// Atomic level: EXAMPLE SHOWCASE

//

// This file demonstrates the Field component from the form package.

// Field is a container for form elements with label, control, and help text.

// Supports horizontal layout, grouped controls, and addons.

//

// Field props:

// - Grouped: Boolean to place controls side-by-side

// - Horizontal: Boolean for horizontal form layout

// - Addons: Boolean to connect controls seamlessly

//

// Control props:

// - Expanded: Boolean to make control fill available space

package kitchensink

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	el "github.com/mtzvd/bulma-templ/elements"
	fo "github.com/mtzvd/bulma-templ/form"
)

// FieldExamples showcases Field component grouping and expansion.
func FieldExamples() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Block(el.BlockProps{}, el.Items{TitleH3("is-4", "Field (Grouped)")}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Grouped fields").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = fo.Field(
			fo.FieldProps{Grouped: true},
			el.Items{
				fo.Control(
					fo.ControlProps{},
					el.Items{
						fo.Input(
							fo.InputProps{
								Type:        "text",
								Placeholder: "Find a repository",
							},
						),
					},
				),
				fo.Control(
					fo.ControlProps{},
					el.Items{
						el.Button(
							el.ButtonProps{Color: "is-info"},
							el.Items{el.Html("Search")},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Expanded field").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = fo.Field(
			fo.FieldProps{Grouped: true},
			el.Items{
				fo.Control(
					fo.ControlProps{Expanded: true},
					el.Items{
						fo.Input(
							fo.InputProps{
								Type:        "text",
								Placeholder: "Expanded input",
							},
						),
					},
				),
				fo.Control(
					fo.ControlProps{},
					el.Items{
						el.Button(
							el.ButtonProps{Color: "is-primary"},
							el.Items{el.Html("Submit")},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
