// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// FileExamples — comprehensive demonstration of fo.File component family.

// Atomic level: EXAMPLE SHOWCASE

//

// This file demonstrates the File components from the form package.

// File provides file upload input with custom styled button.

//

// File family:

// - File: Main container

// - FileLabel: Wrapper for all file components

// - FileInput: Hidden native file input

// - FileCTA: Call-to-action button area

// - FileIcon: Icon in CTA

// - FileName: Selected filename display

//

// Props:

// - HasName: Boolean to show filename display

// - Size: is-small, is-medium, is-large

// - Color: Bulma semantic colors

// - Boxed: Box style file input

// - Fullwidth: Full width file input

package kitchensink

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	el "github.com/mtzvd/bulma-templ/elements"
	fo "github.com/mtzvd/bulma-templ/form"
)

// FileExamples showcases File component with and without filename display.
func FileExamples() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Block(el.BlockProps{}, el.Items{TitleH3("is-4", "File")}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = fo.Field(
			fo.FieldProps{},
			el.Items{
				fo.Label(
					fo.LabelProps{Text: "Choose a file"},
				),
				fo.Control(
					fo.ControlProps{},
					el.Items{
						fo.File(
							fo.FileProps{},
							el.Items{
								fo.FileLabel(
									fo.FileLabelProps{},
									el.Items{
										fo.FileInput(fo.FileInputProps{}),
										fo.FileCTA(
											fo.FileCTAProps{},
											el.Items{
												fo.FileIcon(
													fo.FileIconProps{},
													el.Items{
														el.Icon(el.IconProps{IconClass: "fas fa-upload"}),
													},
												),
												fo.FileLabel(
													fo.FileLabelProps{},
													el.Items{el.Html("Choose a file...")},
												),
											},
										),
									},
								),
							},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("File with name").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = fo.File(
			fo.FileProps{HasName: true},
			el.Items{
				fo.FileLabel(
					fo.FileLabelProps{},
					el.Items{
						fo.FileInput(fo.FileInputProps{}),
						fo.FileCTA(
							fo.FileCTAProps{},
							el.Items{
								fo.FileIcon(
									fo.FileIconProps{},
									el.Items{
										el.Icon(el.IconProps{IconClass: "fas fa-upload"}),
									},
								),
								fo.FileLabel(
									fo.FileLabelProps{},
									el.Items{el.Html("Choose a file...")},
								),
							},
						),
						fo.FileName(
							fo.FileNameProps{},
							el.Items{el.Html("document.pdf")},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
