// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// GridExamples — comprehensive demonstration of gr.Grid component.

// Atomic level: EXAMPLE SHOWCASE

//

// This file demonstrates the Grid system from the grid package.

// Bulma Grid provides two approaches to CSS Grid-based layouts:

//

// 1. SMART GRID (automatic):

//    - Markup: <div class="grid">

//    - Cells automatically fit and wrap

//    - Optional: is-col-min-X for minimum column width (in 1.5rem increments)

//    - Optional: is-gap-X for spacing

//

// 2. FIXED GRID (explicit columns):

//    - Markup: <div class="fixed-grid has-N-cols"><div class="grid">

//    - Exact column count: has-1-cols through has-12-cols

//    - Cells: is-col-span-X, is-row-span-X

//    - Positioning: is-col-start-X, is-row-start-X

//

// Reference: https://bulma.io/documentation/grid/

package kitchensink

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	el "github.com/mtzvd/bulma-templ/elements"
	gr "github.com/mtzvd/bulma-templ/grid"
)

// GridExamples showcases both Smart Grid and Fixed Grid.
func GridExamples() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Block(el.BlockProps{}, el.Items{TitleH3("is-4", "Grid")}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Smart Grid").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gr.Grid(
			gr.GridProps{},
			el.Items{
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{}, el.Items{el.Html("Cell 1")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{}, el.Items{el.Html("Cell 2")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{}, el.Items{el.Html("Cell 3")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{}, el.Items{el.Html("Cell 4")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{}, el.Items{el.Html("Cell 5")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{}, el.Items{el.Html("Cell 6")})}),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Fixed Grid - 2 columns").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Html(`<div class="fixed-grid has-2-cols">`).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gr.Grid(
			gr.GridProps{},
			el.Items{
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{}, el.Items{el.Html("Cell 1")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{}, el.Items{el.Html("Cell 2")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{}, el.Items{el.Html("Cell 3")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{}, el.Items{el.Html("Cell 4")})}),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Html(`</div>`).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Fixed Grid - 4 columns with spanning").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Html(`<div class="fixed-grid has-4-cols">`).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gr.Grid(
			gr.GridProps{},
			el.Items{
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{}, el.Items{el.Html("Cell 1")})}),
				gr.Cell(gr.CellProps{Attr: templ.Attributes{"class": "is-col-span-2"}}, el.Items{el.Notification(el.NotificationProps{Color: "is-info"}, el.Items{el.Html("Cell 2 (spans 2)")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{}, el.Items{el.Html("Cell 3")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{}, el.Items{el.Html("Cell 4")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{}, el.Items{el.Html("Cell 5")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{}, el.Items{el.Html("Cell 6")})}),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Html(`</div>`).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Fixed Grid - 12 columns").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Html(`<div class="fixed-grid has-12-cols">`).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gr.Grid(
			gr.GridProps{},
			el.Items{
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{Color: "is-primary"}, el.Items{el.Html("1")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{Color: "is-primary"}, el.Items{el.Html("2")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{Color: "is-primary"}, el.Items{el.Html("3")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{Color: "is-primary"}, el.Items{el.Html("4")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{Color: "is-primary"}, el.Items{el.Html("5")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{Color: "is-primary"}, el.Items{el.Html("6")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{Color: "is-primary"}, el.Items{el.Html("7")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{Color: "is-primary"}, el.Items{el.Html("8")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{Color: "is-primary"}, el.Items{el.Html("9")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{Color: "is-primary"}, el.Items{el.Html("10")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{Color: "is-primary"}, el.Items{el.Html("11")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{Color: "is-primary"}, el.Items{el.Html("12")})}),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Html(`</div>`).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Fixed Grid - row spanning").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Html(`<div class="fixed-grid has-4-cols">`).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gr.Grid(
			gr.GridProps{},
			el.Items{
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{}, el.Items{el.Html("Cell 1")})}),
				gr.Cell(gr.CellProps{Attr: templ.Attributes{"class": "is-row-span-2"}}, el.Items{el.Notification(el.NotificationProps{Color: "is-success"}, el.Items{el.Html("Cell 2 (row span 2)")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{}, el.Items{el.Html("Cell 3")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{}, el.Items{el.Html("Cell 4")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{}, el.Items{el.Html("Cell 5")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Notification(el.NotificationProps{}, el.Items{el.Html("Cell 6")})}),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Html(`</div>`).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Smart Grid - with minimum column width (is-col-min-8)").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gr.Grid(
			gr.GridProps{Attr: templ.Attributes{"class": "is-col-min-8"}},
			el.Items{
				gr.Cell(gr.CellProps{}, el.Items{el.Box(el.BoxProps{}, el.Items{el.Html("<p>Cell 1</p>")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Box(el.BoxProps{}, el.Items{el.Html("<p>Cell 2</p>")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Box(el.BoxProps{}, el.Items{el.Html("<p>Cell 3</p>")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Box(el.BoxProps{}, el.Items{el.Html("<p>Cell 4</p>")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Box(el.BoxProps{}, el.Items{el.Html("<p>Cell 5</p>")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Box(el.BoxProps{}, el.Items{el.Html("<p>Cell 6</p>")})}),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Smart Grid - with gap (is-gap-4)").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gr.Grid(
			gr.GridProps{Attr: templ.Attributes{"class": "is-gap-4"}},
			el.Items{
				gr.Cell(gr.CellProps{}, el.Items{el.Box(el.BoxProps{}, el.Items{el.Html("<p>Cell 1</p>")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Box(el.BoxProps{}, el.Items{el.Html("<p>Cell 2</p>")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Box(el.BoxProps{}, el.Items{el.Html("<p>Cell 3</p>")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Box(el.BoxProps{}, el.Items{el.Html("<p>Cell 4</p>")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Box(el.BoxProps{}, el.Items{el.Html("<p>Cell 5</p>")})}),
				gr.Cell(gr.CellProps{}, el.Items{el.Box(el.BoxProps{}, el.Items{el.Html("<p>Cell 6</p>")})}),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
