// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// HeroExamples — comprehensive demonstration of la.Hero component family.

// Atomic level: EXAMPLE SHOWCASE

//

// This file demonstrates the Hero components from the layout package.

// Hero provides full-width banner sections with size and color options.

//

// Hero family:

// - Hero: Main container

// - HeroHead: Optional top section (typically for navbar)

// - HeroBody: Main content area (required)

// - HeroFoot: Optional bottom section (typically for tabs)

//

// Hero props:

// - Color: Bulma semantic colors

// - Size: is-small, is-medium, is-large, is-halfheight, is-fullheight

// - Bold: Boolean for gradient background

package kitchensink

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	el "github.com/mtzvd/bulma-templ/elements"
	la "github.com/mtzvd/bulma-templ/layout"
)

// HeroExamples showcases Hero component color and size variations.
func HeroExamples() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Block(el.BlockProps{}, el.Items{TitleH3("is-4", "Hero")}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = la.Hero(
			la.HeroProps{Color: "is-info"},
			el.Items{
				la.HeroBody(
					la.HeroBodyProps{},
					el.Items{
						TitleH4("is-3", "Info Hero"),
						SubtitleP("is-5", "A simple colored hero section"),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<br>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = la.Hero(
			la.HeroProps{Color: "is-success", Size: "is-medium"},
			el.Items{
				la.HeroBody(
					la.HeroBodyProps{},
					el.Items{
						TitleH4("is-3", "Medium Hero"),
						SubtitleP("is-5", "With is-medium size modifier"),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
