// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// IconExamples — comprehensive demonstration of el.Icon component.

// Atomic level: EXAMPLE SHOWCASE

//

// This file demonstrates the Icon component from the elements package.

// Icon is a wrapper for icon fonts (Font Awesome, Material Icons, etc).

// It provides consistent sizing and color integration with Bulma components.

//

// Icon supports:

// - Size variations (small, normal, medium, large)

// - Color variations (all Bulma semantic colors)

// - Font Awesome classes (or any icon font)

// - Automatic sizing in buttons, inputs, and other components

//

// Each example shows different icon sizes, colors, and usage contexts.

// The examples follow Bulma-Templ canonical patterns:

// - No Bulma classes in el.Html() - only plain text

// - Props-based configuration via el.IconProps

// - Icon font classes passed via IconClass prop

package kitchensink

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	el "github.com/mtzvd/bulma-templ/elements"
)

// IconExample1 demonstrates icon size and color variations.
// Icon supports size modifiers and Bulma semantic colors.
func IconExample1() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Block(
			el.BlockProps{},
			el.Items{
				el.Icon(
					el.IconProps{IconClass: "fas fa-home"},
				),
				el.Icon(
					el.IconProps{IconClass: "fas fa-heart", Color: "is-danger"},
				),
				el.Icon(
					el.IconProps{IconClass: "fas fa-check", Size: "is-small"},
				),
				el.Icon(
					el.IconProps{IconClass: "fas fa-star", Size: "is-medium", Color: "is-warning"},
				),
				el.Icon(
					el.IconProps{IconClass: "fas fa-user", Size: "is-large", Color: "is-primary"},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func IconExample1Code() string {
	return `@el.Block(
	el.BlockProps{},
	el.Items{
		el.Icon(
			el.IconProps{IconClass: "fas fa-home"},
		),
		el.Icon(
			el.IconProps{IconClass: "fas fa-heart", Color: "is-danger"},
		),
		el.Icon(
			el.IconProps{IconClass: "fas fa-check", Size: "is-small"},
		),
		el.Icon(
			el.IconProps{IconClass: "fas fa-star", Size: "is-medium", Color: "is-warning"},
		),
		el.Icon(
			el.IconProps{IconClass: "fas fa-user", Size: "is-large", Color: "is-primary"},
		),
	},
)`
}

// IconExample2 demonstrates icons in buttons.
// Icon component automatically sizes to match button size.
func IconExample2() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Buttons(
			el.ButtonsProps{},
			el.Items{
				el.Button(
					el.ButtonProps{Color: "is-primary"},
					el.Items{
						el.Icon(el.IconProps{IconClass: "fas fa-download"}),
						el.Html("<span>Download</span>"),
					},
				),
				el.Button(
					el.ButtonProps{Color: "is-success"},
					el.Items{
						el.Icon(el.IconProps{IconClass: "fas fa-check"}),
						el.Html("<span>Save</span>"),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func IconExample2Code() string {
	return `@el.Buttons(
	el.ButtonsProps{},
	el.Items{
		el.Button(
			el.ButtonProps{Color: "is-primary"},
			el.Items{
				el.Icon(el.IconProps{IconClass: "fas fa-download"}),
				el.Html("<span>Download</span>"),
			},
		),
		el.Button(
			el.ButtonProps{Color: "is-success"},
			el.Items{
				el.Icon(el.IconProps{IconClass: "fas fa-check"}),
				el.Html("<span>Save</span>"),
			},
		),
	},
)`
}

// IconExamples showcases Icon component variations.
// Demonstrates size, color, and usage in buttons.
func IconExamples() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Block(el.BlockProps{}, el.Items{TitleH3("is-4", "Icon")}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		examples := []ComponentItem{
			{ID: "icon-sizes-colors", Code: IconExample1Code(), Component: IconExample1()},
			{ID: "icon-buttons", Code: IconExample2Code(), Component: IconExample2()},
		}
		for _, example := range examples {
			templ_7745c5c3_Err = ExampleWithCode(example.ID, example.Code, example.Component).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
