// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// ImageExamples — comprehensive demonstration of el.Image component.

// Atomic level: EXAMPLE SHOWCASE

//

// This file demonstrates the Image component from the elements package.

// Image is a responsive image container with fixed aspect ratio support.

// It prevents content jumping during image load and maintains consistent sizing.

//

// Reference: https://bulma.io/documentation/elements/image/

package kitchensink

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	el "github.com/mtzvd/bulma-templ/elements"
)

// ImageExample1 demonstrates fixed square images.
// Image component with fixed dimensions prevents content jumping.
func ImageExample1() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Image(
			el.ImageProps{
				Size: "is-128x128",
				Src:  "https://bulma.io/assets/images/placeholders/128x128.png",
				Alt:  "128x128",
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Image(
			el.ImageProps{
				Size: "is-64x64",
				Src:  "https://bulma.io/assets/images/placeholders/128x128.png",
				Alt:  "64x64",
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Image(
			el.ImageProps{
				Size: "is-32x32",
				Src:  "https://bulma.io/assets/images/placeholders/128x128.png",
				Alt:  "32x32",
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func ImageExample1Code() string {
	return `@el.Image(
	el.ImageProps{
		Size: "is-128x128",
		Src:  "https://bulma.io/assets/images/placeholders/128x128.png",
		Alt:  "128x128",
	},
)
@el.Image(
	el.ImageProps{
		Size: "is-64x64",
		Src:  "https://bulma.io/assets/images/placeholders/128x128.png",
		Alt:  "64x64",
	},
)
@el.Image(
	el.ImageProps{
		Size: "is-32x32",
		Src:  "https://bulma.io/assets/images/placeholders/128x128.png",
		Alt:  "32x32",
	},
)`
}

// ImageExample2 demonstrates rounded images.
// Rounded modifier creates circular images for avatars.
func ImageExample2() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Image(
			el.ImageProps{
				Size:    "is-128x128",
				Src:     "https://bulma.io/assets/images/placeholders/128x128.png",
				Alt:     "Rounded image",
				Rounded: true,
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func ImageExample2Code() string {
	return `@el.Image(
	el.ImageProps{
		Size:    "is-128x128",
		Src:     "https://bulma.io/assets/images/placeholders/128x128.png",
		Alt:     "Rounded image",
		Rounded: true,
	},
)`
}

// ImageExample3 demonstrates responsive images with aspect ratios.
// Maintains 16:9 and 4:3 ratios regardless of container size.
func ImageExample3() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Block(
			el.BlockProps{Attr: templ.Attributes{"style": "max-width: 640px;"}},
			el.Items{
				el.Image(
					el.ImageProps{
						Size: "is-16by9",
						Src:  "https://bulma.io/assets/images/placeholders/1280x960.png",
						Alt:  "16:9 ratio",
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Block(
			el.BlockProps{Attr: templ.Attributes{"style": "max-width: 640px;"}},
			el.Items{
				el.Image(
					el.ImageProps{
						Size: "is-4by3",
						Src:  "https://bulma.io/assets/images/placeholders/1280x960.png",
						Alt:  "4:3 ratio",
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func ImageExample3Code() string {
	return `@el.Block(
	el.BlockProps{Attr: templ.Attributes{"style": "max-width: 640px;"}},
	el.Items{
		el.Image(
			el.ImageProps{
				Size: "is-16by9",
				Src:  "https://bulma.io/assets/images/placeholders/1280x960.png",
				Alt:  "16:9 ratio",
			},
		),
	},
)
@el.Block(
	el.BlockProps{Attr: templ.Attributes{"style": "max-width: 640px;"}},
	el.Items{
		el.Image(
			el.ImageProps{
				Size: "is-4by3",
				Src:  "https://bulma.io/assets/images/placeholders/1280x960.png",
				Alt:  "4:3 ratio",
			},
		),
	},
)`
}

// ImageExamples showcases Image component variations.
func ImageExamples() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Block(el.BlockProps{}, el.Items{TitleH3("is-4", "Image")}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		examples := []ComponentItem{
			{ID: "image-fixed", Code: ImageExample1Code(), Component: ImageExample1()},
			{ID: "image-rounded", Code: ImageExample2Code(), Component: ImageExample2()},
			{ID: "image-ratios", Code: ImageExample3Code(), Component: ImageExample3()},
		}
		for _, example := range examples {
			templ_7745c5c3_Err = ExampleWithCode(example.ID, example.Code, example.Component).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
