// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// ModalExamples — comprehensive demonstration of co.Modal component family.

// Atomic level: EXAMPLE SHOWCASE

//

// This file demonstrates the Modal components from the components package.

// Modal provides overlay dialog boxes for focus-demanding interactions.

//

// IMPORTANT: Bulma-Templ components are stateless and do NOT include JavaScript.

// For this showcase, we use Alpine.js to demonstrate interactive behavior.

// In production, you can use any JavaScript framework or vanilla JS.

//

// Modal family:

// - Modal: Main container (add is-active class to show)

// - ModalBackground: Dark overlay (click to close)

// - ModalContent: Content container (for simple modals)

// - ModalClose: Close button

// - ModalCard: Structured modal with head/body/foot

//

// Reference: https://bulma.io/documentation/components/modal/

package kitchensink

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	co "github.com/mtzvd/bulma-templ/components"
	el "github.com/mtzvd/bulma-templ/elements"
)

// ModalExamples showcases three modal variants with Alpine.js interactivity.
func ModalExamples() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Block(el.BlockProps{}, el.Items{TitleH3("is-4", "Modal")}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div x-data=\"{ basicModal: false, imageModal: false, cardModal: false }\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Block(
			el.BlockProps{},
			el.Items{
				el.Content(
					el.ContentProps{},
					el.Items{
						el.Html(`<p><strong>Note:</strong> Bulma-Templ components don't include JavaScript. This showcase uses Alpine.js to demonstrate modal behavior. You can use any JavaScript solution in your project.</p>`),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Launch modals").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Block(
			el.BlockProps{},
			el.Items{
				el.Html(`<div class="buttons">`),
				el.Button(
					el.ButtonProps{Color: "is-primary", Attr: templ.Attributes{"@click": "basicModal = true"}},
					el.Items{el.Html("Launch basic modal")},
				),
				el.Button(
					el.ButtonProps{Color: "is-info", Attr: templ.Attributes{"@click": "imageModal = true"}},
					el.Items{el.Html("Launch image modal")},
				),
				el.Button(
					el.ButtonProps{Color: "is-success", Attr: templ.Attributes{"@click": "cardModal = true"}},
					el.Items{el.Html("Launch card modal")},
				),
				el.Html(`</div>`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Modal(
			co.ModalProps{
				Attr: templ.Attributes{
					":class": "{ 'is-active': basicModal }",
				},
			},
			el.Items{
				co.ModalBackground(
					co.ModalBackgroundProps{
						Attr: templ.Attributes{"@click": "basicModal = false"},
					},
				),
				co.ModalContent(
					co.ModalContentProps{},
					el.Items{
						el.Box(
							el.BoxProps{},
							el.Items{
								el.Html(`<p class="title">Basic Modal</p>`),
								el.Html(`<p>This is a simple modal with content inside a Box component.</p>`),
								el.Html(`<p>Click the X button, background, or press ESC to close.</p>`),
							},
						),
					},
				),
				co.ModalClose(
					co.ModalCloseProps{
						Size: "is-large",
						Attr: templ.Attributes{
							"@click":       "basicModal = false",
							"@keydown.esc": "basicModal = false",
						},
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Modal(
			co.ModalProps{
				Attr: templ.Attributes{
					":class": "{ 'is-active': imageModal }",
				},
			},
			el.Items{
				co.ModalBackground(
					co.ModalBackgroundProps{
						Attr: templ.Attributes{"@click": "imageModal = false"},
					},
				),
				co.ModalContent(
					co.ModalContentProps{},
					el.Items{
						el.Html(`<p class="image is-4by3">
							<img src="https://bulma.io/assets/images/placeholders/1280x960.png" alt="Example image">
						</p>`),
					},
				),
				co.ModalClose(
					co.ModalCloseProps{
						Size: "is-large",
						Attr: templ.Attributes{
							"@click":       "imageModal = false",
							"@keydown.esc": "imageModal = false",
						},
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Modal(
			co.ModalProps{
				Attr: templ.Attributes{
					":class": "{ 'is-active': cardModal }",
				},
			},
			el.Items{
				co.ModalBackground(
					co.ModalBackgroundProps{
						Attr: templ.Attributes{"@click": "cardModal = false"},
					},
				),
				co.ModalCard(
					co.ModalCardProps{},
					el.Items{
						co.ModalCardHead(
							co.ModalCardHeadProps{},
							el.Items{
								el.Html(`<p class="modal-card-title">Card Modal Title</p>`),
								el.Delete(
									el.DeleteProps{
										Attr: templ.Attributes{"@click": "cardModal = false"},
									},
								),
							},
						),
						co.ModalCardBody(
							co.ModalCardBodyProps{},
							el.Items{
								el.Content(
									el.ContentProps{},
									el.Items{
										el.Html(`<h1>Hello World</h1>`),
										el.Html(`<p>This modal uses the <strong>modal-card</strong> structure.</p>`),
										el.Html(`<p>It has a header with a title and delete button, a body section for content, and a footer with action buttons.</p>`),
									},
								),
							},
						),
						co.ModalCardFoot(
							co.ModalCardFootProps{},
							el.Items{
								el.Html(`<div class="buttons">`),
								el.Button(
									el.ButtonProps{Color: "is-success"},
									el.Items{el.Html("Save changes")},
								),
								el.Button(
									el.ButtonProps{Attr: templ.Attributes{"@click": "cardModal = false"}},
									el.Items{el.Html("Cancel")},
								),
								el.Html(`</div>`),
							},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
