// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// NotificationExamples — comprehensive demonstration of el.Notification component.

// Atomic level: EXAMPLE SHOWCASE

//

// This file demonstrates the Notification component from the elements package.

// Notification is a colored alert/message container for displaying feedback to users.

// It supports all Bulma semantic colors and can include a delete button.

//

// Notification supports:

// - Color variations (all Bulma semantic colors)

// - Delete button integration

// - Light color variants

// - Can contain any content

//

// Each example shows different notification colors.

// The examples follow Bulma-Templ canonical patterns:

// - No Bulma classes in el.Html() - only plain text

// - Props-based configuration via el.NotificationProps

// - Color passed via Color prop

package kitchensink

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import el "github.com/mtzvd/bulma-templ/elements"

// NotificationExample1 demonstrates notification color variations.
// Notification supports all Bulma semantic colors.
func NotificationExample1() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Notification(
			el.NotificationProps{},
			el.Items{el.Html("Default notification")},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Notification(
			el.NotificationProps{Color: "is-primary"},
			el.Items{el.Html("Primary notification")},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Notification(
			el.NotificationProps{Color: "is-info"},
			el.Items{el.Html("Info notification")},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Notification(
			el.NotificationProps{Color: "is-success"},
			el.Items{el.Html("Success notification")},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Notification(
			el.NotificationProps{Color: "is-warning"},
			el.Items{el.Html("Warning notification")},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = el.Notification(
			el.NotificationProps{Color: "is-danger"},
			el.Items{el.Html("Danger notification")},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func NotificationExample1Code() string {
	return `@el.Notification(
	el.NotificationProps{},
	el.Items{el.Html("Default notification")},
)
@el.Notification(
	el.NotificationProps{Color: "is-primary"},
	el.Items{el.Html("Primary notification")},
)
@el.Notification(
	el.NotificationProps{Color: "is-info"},
	el.Items{el.Html("Info notification")},
)
@el.Notification(
	el.NotificationProps{Color: "is-success"},
	el.Items{el.Html("Success notification")},
)
@el.Notification(
	el.NotificationProps{Color: "is-warning"},
	el.Items{el.Html("Warning notification")},
)
@el.Notification(
	el.NotificationProps{Color: "is-danger"},
	el.Items{el.Html("Danger notification")},
)`
}

// NotificationExamples showcases Notification component color variations.
// Demonstrates all semantic color options available.
func NotificationExamples() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Block(el.BlockProps{}, el.Items{TitleH3("is-4", "Notification")}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		examples := []ComponentItem{
			{ID: "notification-colors", Code: NotificationExample1Code(), Component: NotificationExample1()},
		}
		for _, example := range examples {
			templ_7745c5c3_Err = ExampleWithCode(example.ID, example.Code, example.Component).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
