// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// KitchenSinkPage — comprehensive showcase of all Bulma-Templ components.

// Atomic level: ORGANISM

//

// This page demonstrates all available components from the Bulma-Templ library,

// organized by package (Elements, Components, Form, Columns, Layout).

// Each component includes 3-4 variations showcasing different props and use cases.

//

// TODO: Implement code display functionality similar to Elements section for the following sections:

// - Components (Breadcrumb, Card, Dropdown, Menu, Message, Modal, Navbar, Pagination, Panel, Tabs)

// - Form (Checkbox, Control, Field, File, Help, Input, Label, Radio, Select, Textarea)

// - Columns

// - Grid

// - Layout (Container, Footer, Hero, Level, Media, Section)

package kitchensink

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	co "github.com/mtzvd/bulma-templ/components"
	el "github.com/mtzvd/bulma-templ/elements"
	la "github.com/mtzvd/bulma-templ/layout"
)

// ------------------------------------------------
// Main Page
// ------------------------------------------------
func Page() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html class=\"has-navbar-fixed-top\" x-data=\"{ darkMode: window.matchMedia('(prefers-color-scheme: dark)').matches, menuOpen: false }\" :class=\"{ 'theme-dark': darkMode }\"><head>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = PageHead().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = PageNavbar().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = la.Hero(
			la.HeroProps{
				Color: "is-primary",
				Size:  "is-medium",
			},
			el.Items{
				la.HeroBody(
					la.HeroBodyProps{},
					el.Items{
						la.Container(
							la.ContainerProps{},
							el.Items{
								TitleH1("is-1", "Bulma-Templ Kitchen Sink"),
								SubtitleP("is-3", "Comprehensive component showcase"),
							},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = la.Section(
			la.SectionProps{},
			el.Items{
				la.Container(
					la.ContainerProps{},
					el.Items{
						ElementsShowcase(),
						ComponentsShowcase(),
						FormShowcase(),
						ColumnsShowcase(),
						GridShowcase(),
						LayoutShowcase(),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = PageFooter().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ------------------------------------------------
// Page Head
// ------------------------------------------------
func PageHead() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>Bulma-Templ Kitchen Sink</title><link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bulma@1.0.4/css/bulma.min.css\"><link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\"><script defer src=\"https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js\"></script><style>\r\n\t\thtml {\r\n\t\t\tscroll-behavior: smooth;\r\n\t\t}\r\n\t</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ------------------------------------------------
// Navbar
// ------------------------------------------------
func PageNavbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = co.Navbar(
			co.NavbarProps{
				Color: "is-dark",
				Fixed: "is-fixed-top",
			},
			el.Items{
				co.NavbarBrand(
					co.NavbarBrandProps{},
					el.Items{
						co.NavbarItem(
							co.NavbarItemProps{Href: "#"},
							el.Items{el.Html("<strong>Bulma-Templ</strong>")},
						),
						co.NavbarBurger(
							co.NavbarBurgerProps{
								Attr: templ.Attributes{
									"@click":         "menuOpen = !menuOpen",
									":class":         "{ 'is-active': menuOpen }",
									"aria-expanded":  "false",
									":aria-expanded": "menuOpen.toString()",
								},
							},
						),
					},
				),
				co.NavbarMenu(
					co.NavbarMenuProps{
						Attr: templ.Attributes{
							":class": "{ 'is-active': menuOpen }",
						},
					},
					el.Items{
						co.NavbarStart(
							co.NavbarStartProps{},
							el.Items{
								co.NavbarItem(
									co.NavbarItemProps{
										Hoverable: true,
										Attr:      templ.Attributes{"class": "has-dropdown"},
									},
									el.Items{
										co.NavbarLink(
											co.NavbarLinkProps{Attr: templ.Attributes{"href": "#elements"}},
											el.Items{el.Html("Elements")},
										),
										co.NavbarDropdown(
											co.NavbarDropdownProps{},
											el.Items{
												co.NavbarItem(co.NavbarItemProps{Href: "#block"}, el.Items{el.Html("Block")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#box"}, el.Items{el.Html("Box")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#button"}, el.Items{el.Html("Button")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#content"}, el.Items{el.Html("Content")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#delete"}, el.Items{el.Html("Delete")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#icon"}, el.Items{el.Html("Icon")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#image"}, el.Items{el.Html("Image")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#notification"}, el.Items{el.Html("Notification")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#progress"}, el.Items{el.Html("Progress")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#table"}, el.Items{el.Html("Table")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#tag"}, el.Items{el.Html("Tag")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#title"}, el.Items{el.Html("Title")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#skeleton"}, el.Items{el.Html("Skeleton")}),
											},
										),
									},
								),
								co.NavbarItem(
									co.NavbarItemProps{
										Hoverable: true,
										Attr:      templ.Attributes{"class": "has-dropdown"},
									},
									el.Items{
										co.NavbarLink(
											co.NavbarLinkProps{Attr: templ.Attributes{"href": "#components"}},
											el.Items{el.Html("Components")},
										),
										co.NavbarDropdown(
											co.NavbarDropdownProps{},
											el.Items{
												co.NavbarItem(co.NavbarItemProps{Href: "#breadcrumb"}, el.Items{el.Html("Breadcrumb")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#card"}, el.Items{el.Html("Card")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#dropdown"}, el.Items{el.Html("Dropdown")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#menu"}, el.Items{el.Html("Menu")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#message"}, el.Items{el.Html("Message")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#modal"}, el.Items{el.Html("Modal")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#navbar"}, el.Items{el.Html("Navbar")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#pagination"}, el.Items{el.Html("Pagination")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#panel"}, el.Items{el.Html("Panel")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#tabs"}, el.Items{el.Html("Tabs")}),
											},
										),
									},
								),
								co.NavbarItem(
									co.NavbarItemProps{
										Hoverable: true,
										Attr:      templ.Attributes{"class": "has-dropdown"},
									},
									el.Items{
										co.NavbarLink(
											co.NavbarLinkProps{Attr: templ.Attributes{"href": "#form"}},
											el.Items{el.Html("Form")},
										),
										co.NavbarDropdown(
											co.NavbarDropdownProps{},
											el.Items{
												co.NavbarItem(co.NavbarItemProps{Href: "#form-general"}, el.Items{el.Html("General")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#input"}, el.Items{el.Html("Input")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#textarea"}, el.Items{el.Html("Textarea")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#select"}, el.Items{el.Html("Select")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#checkbox"}, el.Items{el.Html("Checkbox")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#radio"}, el.Items{el.Html("Radio")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#file"}, el.Items{el.Html("File")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#field"}, el.Items{el.Html("Field")}),
											},
										),
									},
								),
								co.NavbarItem(
									co.NavbarItemProps{Href: "#columns"},
									el.Items{el.Html("Columns")},
								),
								co.NavbarItem(
									co.NavbarItemProps{Href: "#grid"},
									el.Items{el.Html("Grid")},
								),
								co.NavbarItem(
									co.NavbarItemProps{
										Hoverable: true,
										Attr:      templ.Attributes{"class": "has-dropdown"},
									},
									el.Items{
										co.NavbarLink(
											co.NavbarLinkProps{Attr: templ.Attributes{"href": "#layout"}},
											el.Items{el.Html("Layout")},
										),
										co.NavbarDropdown(
											co.NavbarDropdownProps{},
											el.Items{
												co.NavbarItem(co.NavbarItemProps{Href: "#container"}, el.Items{el.Html("Container")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#footer"}, el.Items{el.Html("Footer")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#section"}, el.Items{el.Html("Section")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#hero"}, el.Items{el.Html("Hero")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#level"}, el.Items{el.Html("Level")}),
												co.NavbarItem(co.NavbarItemProps{Href: "#media"}, el.Items{el.Html("Media")}),
											},
										),
									},
								),
							},
						),
						co.NavbarEnd(
							co.NavbarEndProps{},
							el.Items{
								co.NavbarItem(
									co.NavbarItemProps{},
									el.Items{
										el.Button(
											el.ButtonProps{
												Attr: templ.Attributes{
													"@click":      "darkMode = !darkMode",
													":aria-label": "darkMode ? 'Switch to light mode' : 'Switch to dark mode'",
												},
											},
											el.Items{
												el.Icon(
													el.IconProps{
														IconClass: "fas fa-moon",
														Attr: templ.Attributes{
															"x-show": "!darkMode",
														},
													},
												),
												el.Icon(
													el.IconProps{
														IconClass: "fas fa-sun",
														Attr: templ.Attributes{
															"x-show": "darkMode",
														},
													},
												),
											},
										),
									},
								),
							},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ------------------------------------------------
// Footer
// ------------------------------------------------
func PageFooter() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = la.Footer(
			la.FooterProps{},
			el.Items{
				la.Container(
					la.ContainerProps{},
					el.Items{
						el.Block(
							el.BlockProps{
								Attr: templ.Attributes{
									"class": "has-text-centered",
								},
							},
							el.Items{
								FooterText(),
							},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func FooterText() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<p><strong>Bulma-Templ</strong> Kitchen Sink. Built with <a href=\"https://bulma.io\">Bulma</a> and <a href=\"https://templ.guide\">Templ</a>.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ================================================
// SHOWCASE SECTIONS
// ================================================

// ComponentItem defines a component example with its ID for navigation
type ComponentItem struct {
	ID        string
	Code      string
	Component templ.Component
}

// ExampleWithCode wraps a single example with code display functionality
func ExampleWithCode(id string, code string, component templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		attrs := templ.Attributes{"id": id}
		if code != "" {
			attrs["x-data"] = "{ showCode: false }"
			attrs["class"] = "is-relative"
		}
		templ_7745c5c3_Err = el.Block(
			el.BlockProps{Attr: attrs},
			el.Items{
				// Code toggle button
				func() templ.Component {
					if code != "" {
						return el.Block(
							el.BlockProps{
								Attr: templ.Attributes{"style": "position: absolute; top: 0; right: -2rem; z-index: 10;"},
							},
							el.Items{
								el.Button(
									el.ButtonProps{
										Size: "is-small",
										Attr: templ.Attributes{
											"@click": "showCode = !showCode",
											":title": "showCode ? 'Hide code' : 'Show code'",
										},
									},
									el.Items{
										el.Icon(el.IconProps{IconClass: "fas fa-code", Size: "is-small"}),
									},
								),
							},
						)
					}
					return nil
				}(),
				// The component itself
				component,
				// Code display
				func() templ.Component {
					if code != "" {
						return el.Block(
							el.BlockProps{
								Attr: templ.Attributes{
									"x-show":       "showCode",
									"x-transition": "",
								},
							},
							el.Items{
								el.Html(`<textarea class="textarea is-family-code" readonly rows="8" style="font-size: 0.85rem; resize: vertical;">` + code + `</textarea>`),
								el.Button(
									el.ButtonProps{
										Color: "is-primary",
										Size:  "is-small",
										Attr: templ.Attributes{
											"@click": "navigator.clipboard.writeText(`" + code + "`)",
											"class":  "mt-2",
										},
									},
									el.Items{
										el.Icon(el.IconProps{IconClass: "fas fa-copy", Size: "is-small"}),
										el.Html("<span>Copy code</span>"),
									},
								),
							},
						)
					}
					return nil
				}(),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// DemoSectionProps defines the structure for a showcase section header.
type DemoSectionProps struct {
	ID       string
	Title    string
	Subtitle string
}

// DemoSection wraps a showcase section with standardized header (hr, title, subtitle)
// and renders child items (example components).
// Each item is wrapped in el.Box for visual separation.
func DemoSection(props DemoSectionProps, items []ComponentItem) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var7 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var7 == nil {
			templ_7745c5c3_Var7 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		// Build section content with boxed items
		sectionItems := make(el.Items, 0, len(items)+2)

		// Wrap title and subtitle in Block for proper spacing
		sectionItems = append(sectionItems, el.Block(
			el.BlockProps{},
			el.Items{
				TitleH2("is-2", props.Title),
				SubtitleP("5", props.Subtitle),
			},
		))

		// Wrap each example in a Block with ID and code attributes
		for _, item := range items {
			attrs := templ.Attributes{"id": item.ID}
			if item.Code != "" {
				attrs["x-data"] = "{ showCode: false }"
				attrs["class"] = "is-relative"
			}

			// Build example content
			exampleContent := el.Items{}

			// Add code toggle button if code exists
			if item.Code != "" {
				exampleContent = append(exampleContent,
					el.Block(
						el.BlockProps{
							Attr: templ.Attributes{"style": "position: absolute; top: 0; right: 0; z-index: 10;"},
						},
						el.Items{
							el.Button(
								el.ButtonProps{
									Size: "is-small",
									Attr: templ.Attributes{
										"@click": "showCode = !showCode",
										":title": "showCode ? 'Hide code' : 'Show code'",
									},
								},
								el.Items{
									el.Icon(el.IconProps{IconClass: "fas fa-code", Size: "is-small"}),
								},
							),
						},
					),
				)
			}

			// Add the component itself
			exampleContent = append(exampleContent, item.Component)

			// Add code display if code exists
			if item.Code != "" {
				exampleContent = append(exampleContent,
					el.Block(
						el.BlockProps{
							Attr: templ.Attributes{
								"x-show":       "showCode",
								"x-transition": "",
							},
						},
						el.Items{
							el.Html(`<textarea class="textarea is-family-code" readonly rows="8" style="font-size: 0.85rem; resize: vertical;">` + item.Code + `</textarea>`),
							el.Button(
								el.ButtonProps{
									Color: "is-primary",
									Size:  "is-small",
									Attr: templ.Attributes{
										"@click": "navigator.clipboard.writeText(`" + item.Code + "`)",
										"class":  "mt-2",
									},
								},
								el.Items{
									el.Icon(el.IconProps{IconClass: "fas fa-copy", Size: "is-small"}),
									el.Html("<span>Copy code</span>"),
								},
							),
						},
					),
				)
			}

			sectionItems = append(sectionItems, el.Block(
				el.BlockProps{Attr: attrs},
				exampleContent,
			))
		}

		sectionItems = append(sectionItems, el.Html("<hr class='my-6'/>"))
		templ_7745c5c3_Err = la.Section(
			la.SectionProps{
				Attr: templ.Attributes{
					"id": props.ID,
				},
			},
			sectionItems,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func ElementsShowcase() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var8 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var8 == nil {
			templ_7745c5c3_Var8 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = DemoSection(
			DemoSectionProps{
				ID:       "elements",
				Title:    "Elements Package",
				Subtitle: "Core visual elements and atoms",
			},
			[]ComponentItem{
				{ID: "block", Component: BlockExamples()},
				{ID: "box", Component: BoxExamples()},
				{ID: "button", Component: ButtonExamples()},
				{ID: "content", Component: ContentExamples()},
				{ID: "delete", Component: DeleteExamples()},
				{ID: "icon", Component: IconExamples()},
				{ID: "image", Component: ImageExamples()},
				{ID: "notification", Component: NotificationExamples()},
				{ID: "progress", Component: ProgressExamples()},
				{ID: "table", Component: TableExamples()},
				{ID: "tag", Component: TagExamples()},
				{ID: "title", Component: TitleExamples()},
				{ID: "skeleton", Component: SkeletonExamples()},
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func ComponentsShowcase() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var9 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var9 == nil {
			templ_7745c5c3_Var9 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = DemoSection(
			DemoSectionProps{
				ID:       "components",
				Title:    "Components Package",
				Subtitle: "Composite UI organisms",
			},
			[]ComponentItem{
				{ID: "breadcrumb", Component: BreadcrumbExamples()},
				{ID: "card", Component: CardExamples()},
				{ID: "dropdown", Component: DropdownExamples()},
				{ID: "menu", Component: MenuExamples()},
				{ID: "message", Component: MessageExamples()},
				{ID: "modal", Component: ModalExamples()},
				{ID: "navbar", Component: NavbarExamples()},
				{ID: "pagination", Component: PaginationExamples()},
				{ID: "panel", Component: PanelExamples()},
				{ID: "tabs", Component: TabsExamples()},
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func FormShowcase() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var10 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var10 == nil {
			templ_7745c5c3_Var10 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = DemoSection(
			DemoSectionProps{
				ID:       "form",
				Title:    "Form Package",
				Subtitle: "Form elements and controls",
			},
			[]ComponentItem{
				{ID: "form-general", Component: FormGeneralExamples()},
				{ID: "input", Component: InputExamples()},
				{ID: "textarea", Component: TextareaExamples()},
				{ID: "select", Component: SelectExamples()},
				{ID: "checkbox", Component: CheckboxExamples()},
				{ID: "radio", Component: RadioExamples()},
				{ID: "file", Component: FileExamples()},
				{ID: "field", Component: FieldExamples()},
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func ColumnsShowcase() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var11 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var11 == nil {
			templ_7745c5c3_Var11 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = DemoSection(
			DemoSectionProps{
				ID:       "columns",
				Title:    "Columns Package",
				Subtitle: "Flexbox-based grid system",
			},
			[]ComponentItem{
				{ID: "columns", Component: ColumnsExamples()},
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func GridShowcase() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var12 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var12 == nil {
			templ_7745c5c3_Var12 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = DemoSection(
			DemoSectionProps{
				ID:       "grid",
				Title:    "Grid Package",
				Subtitle: "CSS Grid-based layout system (Smart Grid and Fixed Grid)",
			},
			[]ComponentItem{
				{ID: "grid", Component: GridExamples()},
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func LayoutShowcase() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var13 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var13 == nil {
			templ_7745c5c3_Var13 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = DemoSection(
			DemoSectionProps{
				ID:       "layout",
				Title:    "Layout Package",
				Subtitle: "Structural layout components",
			},
			[]ComponentItem{
				{ID: "container", Component: ContainerExamples()},
				{ID: "footer", Component: FooterExamples()},
				{ID: "section", Component: SectionExamples()},
				{ID: "hero", Component: HeroExamples()},
				{ID: "level", Component: LevelExamples()},
				{ID: "media", Component: MediaExamples()},
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
