// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// RadioExamples — comprehensive demonstration of fo.Radio component.

// Atomic level: EXAMPLE SHOWCASE

//

// This file demonstrates the Radio component from the form package.

// Radio provides mutually exclusive selection within a group.

//

// Radio props:

// - Disabled: Boolean state

// - Attr: templ.Attributes for name, value, checked, etc

//

// Content is the label text that appears after radio button.

// All radios in same group must have same name attribute.

package kitchensink

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	el "github.com/mtzvd/bulma-templ/elements"
	fo "github.com/mtzvd/bulma-templ/form"
)

// RadioExamples showcases Radio component grouping.
func RadioExamples() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Block(el.BlockProps{}, el.Items{TitleH3("is-4", "Radio")}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = fo.Field(
			fo.FieldProps{},
			el.Items{
				fo.Label(
					fo.LabelProps{Text: "Choose an option:"},
				),
				fo.Control(
					fo.ControlProps{},
					el.Items{
						fo.Radio(
							fo.RadioProps{Attr: templ.Attributes{"name": "answer"}},
							el.Items{el.Html("Yes")},
						),
					},
				),
				fo.Control(
					fo.ControlProps{},
					el.Items{
						fo.Radio(
							fo.RadioProps{Attr: templ.Attributes{"name": "answer"}},
							el.Items{el.Html("No")},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = fo.Field(
			fo.FieldProps{},
			el.Items{
				fo.Label(
					fo.LabelProps{Text: "Select size:"},
				),
				fo.Control(
					fo.ControlProps{},
					el.Items{
						fo.Radio(
							fo.RadioProps{Attr: templ.Attributes{"name": "size"}},
							el.Items{el.Html("Small")},
						),
					},
				),
				fo.Control(
					fo.ControlProps{},
					el.Items{
						fo.Radio(
							fo.RadioProps{Attr: templ.Attributes{"name": "size"}},
							el.Items{el.Html("Medium")},
						),
					},
				),
				fo.Control(
					fo.ControlProps{},
					el.Items{
						fo.Radio(
							fo.RadioProps{Attr: templ.Attributes{"name": "size"}},
							el.Items{el.Html("Large")},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
