// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// SelectExamples — comprehensive demonstration of fo.Select component.

// Atomic level: EXAMPLE SHOWCASE

//

// This file demonstrates the Select component from the form package.

// Select provides dropdown selection with single or multiple options.

//

// Select props:

// - Multiple: Boolean for multiple selection

// - Size: is-small, is-medium, is-large

// - Color: is-primary, is-danger, is-success

// - Disabled: Boolean state

//

// Content is HTML <option> elements inside Select.

package kitchensink

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	el "github.com/mtzvd/bulma-templ/elements"
	fo "github.com/mtzvd/bulma-templ/form"
)

// SelectExamples showcases Select component single and multiple modes.
func SelectExamples() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Block(el.BlockProps{}, el.Items{TitleH3("is-4", "Select")}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = fo.Field(
			fo.FieldProps{},
			el.Items{
				fo.Label(
					fo.LabelProps{Text: "Country"},
				),
				fo.Control(
					fo.ControlProps{},
					el.Items{
						fo.Select(
							fo.SelectProps{},
							el.Items{
								el.Html(`
								<option>Select country</option>
								<option>United States</option>
								<option>United Kingdom</option>
								<option>Canada</option>
								<option>Germany</option>
							`),
							},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Multiple select").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = fo.Control(
			fo.ControlProps{},
			el.Items{
				fo.Select(
					fo.SelectProps{Multiple: true},
					el.Items{
						el.Html(`
						<option>Option 1</option>
						<option>Option 2</option>
						<option>Option 3</option>
						<option>Option 4</option>
						<option>Option 5</option>
					`),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
