// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// SkeletonExamples — comprehensive demonstration of el.SkeletonBlock and el.SkeletonLines components.

// Atomic level: EXAMPLE SHOWCASE

//

// This file demonstrates the Skeleton components from the elements package.

// Skeleton provides loading placeholders that indicate content is being loaded.

// Modern UX pattern for reducing perceived loading time.

//

// Skeleton components:

// - SkeletonBlock: Single animated placeholder block

// - SkeletonLines: Multiple animated placeholder lines

//

// Each example shows different skeleton usage patterns.

// The examples follow Bulma-Templ canonical patterns:

// - No Bulma classes in el.Html() - only plain text

// - Props-based configuration via el.SkeletonBlockProps/el.SkeletonLinesProps

// - Skeleton wraps actual content which determines placeholder shape

package kitchensink

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import el "github.com/mtzvd/bulma-templ/elements"

// SkeletonExample1 demonstrates skeleton block for large content areas.
// SkeletonBlock creates animated placeholder for images or cards.
func SkeletonExample1() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.SkeletonBlock(
			el.SkeletonBlockProps{},
			el.Items{
				el.Html(`<div style="height: 200px; width: 100%;"></div>`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func SkeletonExample1Code() string {
	return `@el.SkeletonBlock(
	el.SkeletonBlockProps{},
	el.Items{
		el.Html(\` + "`" + `<div style="height: 200px; width: 100%;"></div>\` + "`" + `),
	},
)`
}

// SkeletonExample2 demonstrates skeleton lines for text content.
// SkeletonLines creates multiple animated line placeholders for paragraphs.
func SkeletonExample2() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.SkeletonLines(
			el.SkeletonLinesProps{},
			el.Items{
				el.Html("<div></div>"),
				el.Html("<div></div>"),
				el.Html("<div></div>"),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func SkeletonExample2Code() string {
	return `@el.SkeletonLines(
	el.SkeletonLinesProps{},
	el.Items{
		el.Html("<div></div>"),
		el.Html("<div></div>"),
		el.Html("<div></div>"),
	},
)`
}

// SkeletonExamples showcases Skeleton component variations.
// Demonstrates block and line skeleton loading states.
func SkeletonExamples() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Block(el.BlockProps{}, el.Items{TitleH3("is-4", "Skeleton")}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		examples := []ComponentItem{
			{ID: "skeleton-block", Code: SkeletonExample1Code(), Component: SkeletonExample1()},
			{ID: "skeleton-lines", Code: SkeletonExample2Code(), Component: SkeletonExample2()},
		}
		for _, example := range examples {
			templ_7745c5c3_Err = ExampleWithCode(example.ID, example.Code, example.Component).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
