// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package kitchensink

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	co "github.com/mtzvd/bulma-templ/components"
	el "github.com/mtzvd/bulma-templ/elements"
)

func TabsExamples() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Block(el.BlockProps{}, el.Items{TitleH3("is-4", "Tabs")}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Default").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Tabs(
			co.TabsProps{},
			el.Items{
				el.Html(`
				<ul>
					<li class="is-active"><a>Pictures</a></li>
					<li><a>Music</a></li>
					<li><a>Videos</a></li>
					<li><a>Documents</a></li>
				</ul>
			`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Centered alignment").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Tabs(
			co.TabsProps{Centered: true},
			el.Items{
				el.Html(`
				<ul>
					<li class="is-active"><a>Pictures</a></li>
					<li><a>Music</a></li>
					<li><a>Videos</a></li>
					<li><a>Documents</a></li>
				</ul>
			`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Right alignment").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Tabs(
			co.TabsProps{Right: true},
			el.Items{
				el.Html(`
				<ul>
					<li class="is-active"><a>Pictures</a></li>
					<li><a>Music</a></li>
					<li><a>Videos</a></li>
					<li><a>Documents</a></li>
				</ul>
			`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("With icons").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Tabs(
			co.TabsProps{Centered: true},
			el.Items{
				el.Html(`
				<ul>
					<li class="is-active">
						<a>
							<span class="icon is-small"><i class="fas fa-image"></i></span>
							<span>Pictures</span>
						</a>
					</li>
					<li>
						<a>
							<span class="icon is-small"><i class="fas fa-music"></i></span>
							<span>Music</span>
						</a>
					</li>
					<li>
						<a>
							<span class="icon is-small"><i class="fas fa-film"></i></span>
							<span>Videos</span>
						</a>
					</li>
					<li>
						<a>
							<span class="icon is-small"><i class="far fa-file-alt"></i></span>
							<span>Documents</span>
						</a>
					</li>
				</ul>
			`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Boxed style").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Tabs(
			co.TabsProps{Boxed: true},
			el.Items{
				el.Html(`
				<ul>
					<li class="is-active">
						<a>
							<span class="icon is-small"><i class="fas fa-image"></i></span>
							<span>Pictures</span>
						</a>
					</li>
					<li>
						<a>
							<span class="icon is-small"><i class="fas fa-music"></i></span>
							<span>Music</span>
						</a>
					</li>
					<li>
						<a>
							<span class="icon is-small"><i class="fas fa-film"></i></span>
							<span>Videos</span>
						</a>
					</li>
					<li>
						<a>
							<span class="icon is-small"><i class="far fa-file-alt"></i></span>
							<span>Documents</span>
						</a>
					</li>
				</ul>
			`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Toggle style").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Tabs(
			co.TabsProps{Toggle: true},
			el.Items{
				el.Html(`
				<ul>
					<li class="is-active">
						<a>
							<span class="icon is-small"><i class="fas fa-image"></i></span>
							<span>Pictures</span>
						</a>
					</li>
					<li>
						<a>
							<span class="icon is-small"><i class="fas fa-music"></i></span>
							<span>Music</span>
						</a>
					</li>
					<li>
						<a>
							<span class="icon is-small"><i class="fas fa-film"></i></span>
							<span>Videos</span>
						</a>
					</li>
					<li>
						<a>
							<span class="icon is-small"><i class="far fa-file-alt"></i></span>
							<span>Documents</span>
						</a>
					</li>
				</ul>
			`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Toggle rounded").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Tabs(
			co.TabsProps{Toggle: true, ToggleRounded: true},
			el.Items{
				el.Html(`
				<ul>
					<li class="is-active">
						<a>
							<span class="icon is-small"><i class="fas fa-image"></i></span>
							<span>Pictures</span>
						</a>
					</li>
					<li>
						<a>
							<span class="icon is-small"><i class="fas fa-music"></i></span>
							<span>Music</span>
						</a>
					</li>
					<li>
						<a>
							<span class="icon is-small"><i class="fas fa-film"></i></span>
							<span>Videos</span>
						</a>
					</li>
				</ul>
			`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Fullwidth").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Tabs(
			co.TabsProps{Fullwidth: true},
			el.Items{
				el.Html(`
				<ul>
					<li>
						<a>
							<span class="icon"><i class="fas fa-angle-left"></i></span>
							<span>Left</span>
						</a>
					</li>
					<li>
						<a>
							<span class="icon"><i class="fas fa-angle-up"></i></span>
							<span>Up</span>
						</a>
					</li>
					<li>
						<a>
							<span>Right</span>
							<span class="icon"><i class="fas fa-angle-right"></i></span>
						</a>
					</li>
				</ul>
			`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Small size").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Tabs(
			co.TabsProps{Size: "is-small"},
			el.Items{
				el.Html(`
				<ul>
					<li class="is-active"><a>Pictures</a></li>
					<li><a>Music</a></li>
					<li><a>Videos</a></li>
					<li><a>Documents</a></li>
				</ul>
			`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Medium size").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Tabs(
			co.TabsProps{Size: "is-medium"},
			el.Items{
				el.Html(`
				<ul>
					<li class="is-active"><a>Pictures</a></li>
					<li><a>Music</a></li>
					<li><a>Videos</a></li>
					<li><a>Documents</a></li>
				</ul>
			`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Large size").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Tabs(
			co.TabsProps{Size: "is-large"},
			el.Items{
				el.Html(`
				<ul>
					<li class="is-active"><a>Pictures</a></li>
					<li><a>Music</a></li>
					<li><a>Videos</a></li>
					<li><a>Documents</a></li>
				</ul>
			`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Combining modifiers (Centered + Boxed + Medium)").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Tabs(
			co.TabsProps{Centered: true, Boxed: true, Size: "is-medium"},
			el.Items{
				el.Html(`
				<ul>
					<li class="is-active">
						<a>
							<span class="icon is-small"><i class="fas fa-image"></i></span>
							<span>Pictures</span>
						</a>
					</li>
					<li>
						<a>
							<span class="icon is-small"><i class="fas fa-music"></i></span>
							<span>Music</span>
						</a>
					</li>
					<li>
						<a>
							<span class="icon is-small"><i class="fas fa-film"></i></span>
							<span>Videos</span>
						</a>
					</li>
					<li>
						<a>
							<span class="icon is-small"><i class="far fa-file-alt"></i></span>
							<span>Documents</span>
						</a>
					</li>
				</ul>
			`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExampleSubheading("Combining modifiers (Toggle + Fullwidth + Large)").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = co.Tabs(
			co.TabsProps{Toggle: true, Fullwidth: true, Size: "is-large"},
			el.Items{
				el.Html(`
				<ul>
					<li class="is-active">
						<a>
							<span class="icon"><i class="fas fa-image"></i></span>
							<span>Pictures</span>
						</a>
					</li>
					<li>
						<a>
							<span class="icon"><i class="fas fa-music"></i></span>
							<span>Music</span>
						</a>
					</li>
					<li>
						<a>
							<span class="icon"><i class="fas fa-film"></i></span>
							<span>Videos</span>
						</a>
					</li>
					<li>
						<a>
							<span class="icon"><i class="far fa-file-alt"></i></span>
							<span>Documents</span>
						</a>
					</li>
				</ul>
			`),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
