// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// TextareaExamples — comprehensive demonstration of fo.Textarea component.

// Atomic level: EXAMPLE SHOWCASE

//

// This file demonstrates the Textarea component from the form package.

// Textarea provides multi-line text input with validation states and sizing.

//

// Textarea props:

// - Placeholder: Placeholder text

// - Color: is-primary, is-danger, is-success (validation states)

// - Size: is-small, is-medium, is-large

// - Rows: Number of visible rows

// - Disabled, Readonly: Boolean states

// - FixedSize: Disable resize handle

//

// Use with Field for labels and Help for guidance text.

package kitchensink

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	el "github.com/mtzvd/bulma-templ/elements"
	fo "github.com/mtzvd/bulma-templ/form"
)

// TextareaExamples showcases Textarea component with validation.
func TextareaExamples() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = el.Block(el.BlockProps{}, el.Items{TitleH3("is-4", "Textarea")}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = fo.Field(
			fo.FieldProps{},
			el.Items{
				fo.Label(
					fo.LabelProps{Text: "Message"},
				),
				fo.Control(
					fo.ControlProps{},
					el.Items{
						fo.Textarea(
							fo.TextareaProps{
								Placeholder: "Enter your message here...",
							},
						),
					},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = fo.Field(
			fo.FieldProps{},
			el.Items{
				fo.Label(
					fo.LabelProps{Text: "Comment"},
				),
				fo.Control(
					fo.ControlProps{},
					el.Items{
						fo.Textarea(
							fo.TextareaProps{
								Placeholder: "Add a comment",
								Color:       "is-primary",
							},
						),
					},
				),
				fo.Help(
					fo.HelpProps{Text: "Maximum 500 characters"},
				),
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
